# Deber — NumPy: 61 métodos esenciales
**Asignatura:** Análisis de Datos  
**Institución:** ESFOT — EPN  
**Docente:** Juan Carlos Gonzalez Ortiz  
**Estudiante:** Alan Reyes

---

Este deber cubre los 61 métodos de NumPy vistos en el curso (18 de clase + 43 nuevos).  
Cada sección explica el método, muestra un ejemplo ejecutable y propone un ejercicio aplicado.

**Instrucciones**
- Reemplaza cada `# TU CODIGO AQUI` con tu solución.
- El notebook debe ejecutarse completo sin errores: `Kernel > Restart & Run All`.
- Entrega el archivo renombrado como `deber_numpy_<tu_nombre>.ipynb`.
- Sin formato adecuado y celdas Markdown intactas, la nota se califica sobre la mitad.



In [1]:
import numpy as np
import os
print('NumPy version:', np.__version__)

NumPy version: 2.4.2


### Creación de arrays: `np.array`, `np.zeros`, `np.ones`, `np.eye`, `np.arange`, `np.linspace`

| Función | Propósito |
|---|---|
| `np.array(lista)` | convierte una lista Python en array NumPy |
| `np.zeros(shape)` | array relleno de ceros |
| `np.ones(shape)` | array relleno de unos |
| `np.eye(n)` | matriz identidad n×n |
| `np.arange(inicio, fin, paso)` | secuencia con paso fijo |
| `np.linspace(inicio, fin, n)` | n valores equiespaciados entre inicio y fin |

In [2]:
print('np.array:   ', np.array([10, 20, 30]))
print('np.zeros:   ', np.zeros((2, 3)))
print('np.ones:    ', np.ones((2, 3)))
print('np.eye(3):  ')
print(np.eye(3))
print('np.arange(0,10,2):   ', np.arange(0, 10, 2))
print('np.linspace(0,1,5):  ', np.linspace(0, 1, 5))

np.array:    [10 20 30]
np.zeros:    [[0. 0. 0.]
 [0. 0. 0.]]
np.ones:     [[1. 1. 1.]
 [1. 1. 1.]]
np.eye(3):  
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
np.arange(0,10,2):    [0 2 4 6 8]
np.linspace(0,1,5):   [0.   0.25 0.5  0.75 1.  ]


In [3]:
# EJERCICIO 1
# Construye la tabla de multiplicar del 3 (del 3x1 al 3x10)
# usando np.arange y operaciones vectorizadas

# 1a. Crea un array con los números del 1 al 10
numeros = np.arange(0, 11, 1)

# 1b. Multiplica por 3
tabla_3 = 3 * numeros

print('Tabla del 3:', tabla_3)

# 1c. Crea una secuencia de 6 ángulos entre 0 y 360 grados (linspace)
angulos = np.linspace(0, 360, 6)
print('Ángulos:', angulos)

Tabla del 3: [ 0  3  6  9 12 15 18 21 24 27 30]
Ángulos: [  0.  72. 144. 216. 288. 360.]


### Aleatoriedad: `np.random.seed`, `np.random.rand`, `np.random.randint`

- `seed(n)` — fija la semilla: garantiza reproducibilidad (mismo seed = mismos números)
- `rand(shape)` — valores flotantes en [0, 1) con distribución uniforme
- `randint(low, high, size)` — enteros aleatorios en [low, high)

In [4]:
np.random.seed(7)
print('rand(3):       ', np.round(np.random.rand(3), 4))
print('randint(1,7,5):', np.random.randint(1, 7, 5))

# Reproducibilidad: mismo seed = mismo resultado
np.random.seed(7)
a = np.random.rand(3)
np.random.seed(7)
b = np.random.rand(3)
print('¿Reproducible?', np.all(a == b))

rand(3):        [0.0763 0.7799 0.4384]
randint(1,7,5): [5 2 1 2 3]
¿Reproducible? True


In [5]:
# EJERCICIO 2
# Simula el resultado de lanzar un dado de 6 caras 20 veces.

import numpy as np

np.random.seed(42)

# 2a. Genera 20 lanzamientos de un dado (valores entre 1 y 6)
lanzamientos = np.random.randint(1, 7, 20)
print('Lanzamientos:', lanzamientos)

# 2b. Cuántas veces salió el número 6?
seis = np.sum(lanzamientos == 6)
print('Veces que salió 6:', seis)

Lanzamientos: [4 5 3 5 5 2 3 3 3 5 4 3 6 5 2 4 6 6 2 4]
Veces que salió 6: 3


### Estructura: `arr.reshape`, `arr.flatten`

- `reshape(n, m)` — cambia la forma sin alterar los datos (n×m debe ser igual al total de elementos)
- `flatten()` — colapsa el array a 1D devolviendo una **copia** independiente

In [6]:
v = np.arange(12)
M = v.reshape(3, 4)
print('arange(12):\n', v)
print('reshape(3,4):\n', M)
print('flatten:\n', M.flatten())

arange(12):
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshape(3,4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flatten:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [7]:
# EJERCICIO 3
# Un sensor registra 24 lecturas horarias. Necesitas reorganizarlas
# en una matriz de 4 filas x 6 columnas (4 bloques de 6 horas).

np.random.seed(1)
lecturas = np.random.randint(15, 35, size=24)  # temperaturas entre 15 y 35

# 3a. Reorganiza en 4x6
bloques = lecturas.reshape(4, 6)
print('Lecturas por bloque (4 bloques x 6 horas):')
print(bloques)

# 3b. Aplana de nuevo para obtener la serie original
serie = lecturas.flatten()
print('\n¿Flatten recupera la serie original?', np.all(serie == lecturas))

Lecturas por bloque (4 bloques x 6 horas):
[[20 26 27 23 24 26]
 [20 30 15 31 16 27]
 [22 28 21 33 20 33]
 [26 25 29 33 19 24]]

¿Flatten recupera la serie original? True


### Estadísticas: `np.sum`, `np.mean`, `np.median`, `np.std`, `np.min`, `np.max`

Todas aceptan el parámetro `axis`:  
- `axis=0` → opera sobre filas (resultado por columna)  
- `axis=1` → opera sobre columnas (resultado por fila)  
- sin `axis` → opera sobre todo el array

In [8]:
notas = np.array([[8.0, 7.5, 9.0],
                  [6.0, 8.5, 7.0],
                  [9.5, 6.5, 8.0]])

print('Media global:         ', np.mean(notas))
print('Media por evaluación: ', np.mean(notas, axis=0))  # por columna
print('Media por estudiante: ', np.mean(notas, axis=1))  # por fila
print('Std global:           ', round(np.std(notas), 4))
print('Min / Max:            ', np.min(notas), '/', np.max(notas))
print('Mediana:              ', np.median(notas))
print('Suma total:           ', np.sum(notas))

Media global:          7.777777777777778
Media por evaluación:  [7.83333333 7.5        8.        ]
Media por estudiante:  [8.16666667 7.16666667 8.        ]
Std global:            1.083
Min / Max:             6.0 / 9.5
Mediana:               8.0
Suma total:            70.0


In [9]:
# EJERCICIO 4
# Ventas semanales de 3 vendedores durante 5 semanas (filas=semanas, cols=vendedores)

np.random.seed(10)
ventas = np.random.randint(50, 200, size=(5, 3))
print('Ventas (5 semanas x 3 vendedores):')
print(ventas)

# 4a. Total de ventas por vendedor (suma por columna)
total_vendedor = np.sum(ventas, axis=0)
print('\nTotal por vendedor:', total_vendedor)

# 4b. Promedio semanal (media por fila)
promedio_semana = np.sum(ventas, axis=1)
print('Promedio semanal: ', np.round(promedio_semana, 1))



Ventas (5 semanas x 3 vendedores):
[[ 59 175  65]
 [114 163 173]
 [163  58 123]
 [ 50  90 165]
 [ 66 150 189]]

Total por vendedor: [452 636 715]
Promedio semanal:  [299 450 344 305 405]


### Multiplicaciones y combinación: `np.dot`, `np.multiply`, `np.concatenate`

| Función | Operación | Cuándo usarla |
|---|---|---|
| `np.multiply(A, B)` | elemento a elemento | máscaras, escalar |
| `np.dot(A, B)` | matricial (filas × columnas) | álgebra lineal, ML |
| `np.concatenate((a, b), axis)` | une arrays a lo largo de un eje | ensamblar datasets |

In [10]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print('A * B  (multiply):')
print(np.multiply(A, B))
print('A @ B  (dot):')
print(np.dot(A, B))

# concatenate
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print('\nconcatenate horizontal:', np.concatenate((x, y)))

M1 = np.ones((2, 3))
M2 = np.zeros((2, 3))
print('concatenate vertical (axis=0):')
print(np.concatenate((M1, M2), axis=0))

A * B  (multiply):
[[ 5 12]
 [21 32]]
A @ B  (dot):
[[19 22]
 [43 50]]

concatenate horizontal: [1 2 3 4 5 6]
concatenate vertical (axis=0):
[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
# EJERCICIO 5
# Calcula el ingreso total por producto:
# ingreso = precio * unidades_vendidas  (elemento a elemento)

precios    = np.array([2.50, 8.00, 1.20, 5.75, 3.40])
unidades   = np.array([120,  45,   300,  80,   200 ])

# 5a. Ingreso por producto (multiply)
ingreso = np.multiply(precios, unidades)
print('Ingreso por producto:', ingreso)
print('Ingreso total:       ', np.sum(ingreso))

# 5b. Combina precios e ingresos en una sola matriz (2 filas x 5 cols)
# Pista: primero reshape cada array a (1,5), luego concatenate con axis=0
tabla = np.concatenate((
    precios.reshape(1, -1),
    ingreso.reshape(1, -1)
), axis=0)
print('\nTabla [precio; ingreso]:')
print(tabla)

Ingreso por producto: [300. 360. 360. 460. 680.]
Ingreso total:        2160.0

Tabla [precio; ingreso]:
[[  2.5    8.     1.2    5.75   3.4 ]
 [300.   360.   360.   460.   680.  ]]


---
## Reestructuración y tipos de dato
Amplía el control sobre la forma y el tipo de los arrays.  
Son esenciales antes de trabajar con Pandas.

### `arr.ravel()` — aplanar a 1D (vista)

`ravel()` devuelve una **vista** del array aplanado: modificar el resultado puede modificar el original.  
`flatten()` (ya conocido) devuelve una **copia** independiente.

| Método | Tipo | Toca el original |
|---|---|---|
| `flatten()` | copia | no |
| `ravel()` | vista | sí |

In [12]:
M = np.array([[1, 2, 3], [4, 5, 6]])
v = M.ravel()
print('ravel:', v)

v[0] = 99
print('Después de modificar v[0]=99, M[0,0]:', M[0, 0], '<-- cambió')

ravel: [1 2 3 4 5 6]
Después de modificar v[0]=99, M[0,0]: 99 <-- cambió


In [13]:
# EJERCICIO 6
# Tienes registros de ventas en 3 semanas x 5 días.
# Necesitas la serie temporal completa (15 valores) para calcular la tendencia.

ventas_sem = np.array([
    [120, 95, 110, 105, 130],
    [115, 100, 125, 90, 140],
    [110, 105, 118, 122, 135]
])

# 6a. Aplana con ravel() para obtener la serie de 15 días
serie = ventas_sem.ravel()
print('Serie temporal:', serie)
print('Promedio del periodo:', round(np.mean(serie), 2))

# 6b. ¿ravel devuelve vista o copia? Verifica modificando serie[0]
serie[0] = 0
print('ventas_sem[0,0] después de modificar serie[0]:', ventas_sem[0, 0])
print('Conclusión: ravel devuelve', 'VISTA' if ventas_sem[0,0]==0 else 'COPIA')

Serie temporal: [120  95 110 105 130 115 100 125  90 140 110 105 118 122 135]
Promedio del periodo: 114.67
ventas_sem[0,0] después de modificar serie[0]: 0
Conclusión: ravel devuelve VISTA


### `np.transpose()` — intercambiar filas y columnas

Convierte un array `(m, n)` en `(n, m)`.  
Equivalente a `arr.T`.

**Caso de uso real:** los datasets llegan como `(features, muestras)` pero los modelos  
esperan `(muestras, features)`. Transpose lo corrige en una línea.

In [14]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print('A shape:', A.shape)
print(A)
print('\nA.T shape:', A.T.shape)
print(np.transpose(A))
print('\n¿A.T == np.transpose(A)?', np.all(A.T == np.transpose(A)))

A shape: (2, 3)
[[1 2 3]
 [4 5 6]]

A.T shape: (3, 2)
[[1 4]
 [2 5]
 [3 6]]

¿A.T == np.transpose(A)? True


In [15]:
# EJERCICIO 7
# Dataset con 3 atributos y 5 muestras — shape (3, 5)
# Los algoritmos esperan (5, 3). Transpón y verifica.

datos = np.array([
    [1.2, 2.4, 0.8, 3.1, 1.9],   # feature 1
    [20,  35,  18,  42,  28 ],   # feature 2
    [0.5, 0.3, 0.8, 0.1, 0.6]   # feature 3
])

print('Shape original:', datos.shape)

# Transpón
datos_T = datos.transpose()
print('Shape transpuesto:', datos_T.shape)

# Primera muestra (fila 0 del transpuesto)
print('Primera muestra [f1, f2, f3]:', datos_T[0])

Shape original: (3, 5)
Shape transpuesto: (5, 3)
Primera muestra [f1, f2, f3]: [ 1.2 20.   0.5]


### `arr.astype()` — convertir tipo de dato

Devuelve una **copia** del array en el nuevo tipo.  
Tipos más comunes: `np.float64`, `np.int32`, `np.bool_`, `str`.

In [16]:
raw = np.array(['1.5', '3.2', '0.8', '4.0'])
print('dtype original:', raw.dtype)

nums = raw.astype(np.float64)
print('dtype convertido:', nums.dtype)
print('Suma:', nums.sum())

# float -> int trunca los decimales
print('Como int32:', nums.astype(np.int32))

dtype original: <U3
dtype convertido: float64
Suma: 9.5
Como int32: [1 3 0 4]


In [17]:
# EJERCICIO 8
# Un CSV exportó calificaciones como strings.

cal_raw = np.array(['8.5', '7.0', '9.2', '6.8', '10.0', '5.5'])

# 8a. Convierte a float64
cal = cal_raw.astype(np.float64)
print('Promedio:', round(np.mean(cal), 2))

# 8b. Convierte a int (nota entera)
cal_int = cal.astype(np.int_)
print('Notas enteras:', cal_int)

# 8c. Crea una máscara booleana: True si aprobó (>= 7)
aprobado = (cal >= 7).astype(np.bool_)
print('Aprobados:', aprobado)

Promedio: 7.83
Notas enteras: [ 8  7  9  6 10  5]
Aprobados: [ True  True  True False  True False]


### `arr.copy()` — copia independiente

La asignación `b = a` crea un **alias**, no una copia.  
Modificar `b` modifica `a`. `copy()` crea un array completamente nuevo.

In [18]:
original = np.array([10, 20, 30, 40, 50])

alias = original          # NO es copia
alias[0] = 999
print('original después de modificar alias:', original)

original2 = np.array([10, 20, 30, 40, 50])
copia = original2.copy()  # sí es copia
copia[0] = 999
print('original2 después de modificar copia:', original2)

original después de modificar alias: [999  20  30  40  50]
original2 después de modificar copia: [10 20 30 40 50]


In [19]:
# EJERCICIO 9
# Simula un aumento de precios del 15% sin alterar los precios base.

precios_base = np.array([5.00, 12.50, 8.75, 3.20, 15.00])

# 9a. Crea una copia independiente
precios_nuevos = precios_base.copy()

# 9b. Aplica el aumento del 15%
precios_nuevos *= 1.15

print('Precios base:       ', precios_base)
print('Precios +15%:       ', np.round(precios_nuevos, 2))
print('Base sin cambio:    ', np.all(precios_base == np.array([5.00, 12.50, 8.75, 3.20, 15.00])))

Precios base:        [ 5.   12.5   8.75  3.2  15.  ]
Precios +15%:        [ 5.75 14.37 10.06  3.68 17.25]
Base sin cambio:     True


---
Funciones matemáticas (ufuncs)
Las ufuncs se aplican elemento a elemento sin loops.  
Están escritas en C: son órdenes de magnitud más rápidas que un `for`.

### `np.sqrt`, `np.exp`, `np.log`, `np.power`

| Función | Descripción | Nota |
|---|---|---|
| `np.sqrt(x)` | raíz cuadrada | equivale a `x**0.5` |
| `np.exp(x)` | exponencial e^x | inversa de log |
| `np.log(x)` | logaritmo natural ln(x) | indefinido para x<=0 |
| `np.power(x, n)` | x^n | equivale a `x**n` |

In [20]:
x = np.array([1.0, 4.0, 9.0, 16.0])
print('sqrt:', np.sqrt(x))
print('power(x,2):', np.power(x, 2))

y = np.array([0.0, 1.0, 2.0, 3.0])
print('exp(y):', np.round(np.exp(y), 4))
print('log(exp(y)) = y:', np.round(np.log(np.exp(y)), 4))

sqrt: [1. 2. 3. 4.]
power(x,2): [  1.  16.  81. 256.]
exp(y): [ 1.      2.7183  7.3891 20.0855]
log(exp(y)) = y: [0. 1. 2. 3.]


In [21]:
# EJERCICIO 10
# Interés compuesto continuo: A = P * e^(r*t)

P = 1000.0
tasas = np.array([0.03, 0.05, 0.08, 0.10, 0.12])
t = 5

# 10a. Calcula el monto final para cada tasa
A = P * np.exp(tasas * t)

print('Capital final por tasa:')
for r, monto in zip(tasas, A):
    print(f'  {r*100:.0f}%: USD {monto:.2f}')

# 10b. ¿Cuántos años necesita la tasa del 5% para duplicar el capital?
# Despeja t de: 2P = P * e^(0.05*t)  ->  t = ln(2) / 0.05
t_doble = np.log(2) / 0.05
print(f'\nAños para duplicar al 5%: {t_doble:.2f}')

Capital final por tasa:
  3%: USD 1161.83
  5%: USD 1284.03
  8%: USD 1491.82
  10%: USD 1648.72
  12%: USD 1822.12

Años para duplicar al 5%: 13.86


### `np.round`, `np.floor`, `np.ceil`, `np.trunc`

| Función | Con 2.7 | Con -2.3 |
|---|---|---|
| `np.round` | 3.0 | -2.0 |
| `np.floor` | 2.0 | -3.0 |
| `np.ceil` | 3.0 | -2.0 |
| `np.trunc` | 2.0 | -2.0 |

In [22]:
v = np.array([-2.7, -1.3, 0.5, 1.3, 2.7])
print('valores:', v)
print('round:  ', np.round(v))
print('floor:  ', np.floor(v))
print('ceil:   ', np.ceil(v))
print('trunc:  ', np.trunc(v))

p = np.array([1.2346, 5.9999, 3.1415])
print('\nround a 2 decimales:', np.round(p, 2))

valores: [-2.7 -1.3  0.5  1.3  2.7]
round:   [-3. -1.  0.  1.  3.]
floor:   [-3. -2.  0.  1.  2.]
ceil:    [-2. -1.  1.  2.  3.]
trunc:   [-2. -1.  0.  1.  2.]

round a 2 decimales: [1.23 6.   3.14]


In [23]:
# EJERCICIO 11
# Sistema de facturación con tres reglas de redondeo distintas.

precio_calculado   = np.array([3.1416, 9.9950, 0.0049, 14.2851])
unidades_pedido    = np.array([2.1,    5.0,    1.9,    3.5   ])
descuento_calculado = np.array([1.999,  0.501,  3.249,  0.001 ])

# 11a. Precio al cliente: redondear a 2 decimales
precio_cliente = np.round(precio_calculado, 2)

# 11b. Unidades a preparar: siempre hacia arriba (no podemos enviar de menos)
unidades_preparar = np.ceil(unidades_pedido)

# 11c. Descuento: truncar (nunca dar más descuento del calculado)
descuento_aplicar = np.trunc(descuento_calculado)

print('Precio cliente:   ', precio_cliente)
print('Unidades preparar:', unidades_preparar)
print('Descuento:        ', descuento_aplicar)

Precio cliente:    [ 3.14  9.99  0.   14.29]
Unidades preparar: [3. 5. 2. 4.]
Descuento:         [1. 0. 3. 0.]


### `np.greater`, `np.equal`, `np.maximum`, `np.minimum`

Son la versión funcional de los operadores `>`, `==`.  
Útiles cuando se pasan funciones como argumento o en pipelines.

- `np.greater(a, b)` → `a > b`  
- `np.equal(a, b)` → `a == b`  
- `np.maximum(a, b)` → el mayor de cada par  
- `np.minimum(a, b)` → el menor de cada par

In [24]:
a = np.array([1, 5, 3, 8, 2])
b = np.array([4, 2, 3, 1, 6])
print('a:', a)
print('b:', b)
print('greater(a,b):', np.greater(a, b))
print('equal(a,b):  ', np.equal(a, b))
print('maximum:     ', np.maximum(a, b))
print('minimum:     ', np.minimum(a, b))

a: [1 5 3 8 2]
b: [4 2 3 1 6]
greater(a,b): [False  True False  True False]
equal(a,b):   [False False  True False False]
maximum:      [4 5 3 8 6]
minimum:      [1 2 3 1 2]


In [25]:
# EJERCICIO 12
# Dos sucursales, 7 días de ventas.

norte = np.array([120, 85, 200, 95, 150, 180, 110])
sur   = np.array([100, 95, 175, 110, 140, 200, 90])

# 12a. Días donde Norte supera a Sur
norte_gana = np.greater(norte, sur)
print('Norte supera a Sur:', norte_gana)

# 12b. Días con ventas idénticas
empate = np.equal(norte, sur)
print('Empate:', empate)

# 12c. Mejor venta de cada día (para el reporte de máximos)
mejor = np.maximum(norte, sur)
print('Mejor por día:', mejor)
print('Total mejor escenario:', mejor.sum())

Norte supera a Sur: [ True False  True False  True False  True]
Empate: [False False False False False False False]
Mejor por día: [120  95 200 110 150 200 110]
Total mejor escenario: 985


---
## Filtrado y selección avanzada
Extiende el boolean indexing con herramientas para transformar  
condiciones en valores y validar datos masivamente.

### `np.where()` — if/else vectorizado

```python
np.where(condición, valor_si_verdadero, valor_si_falso)
```

Evalúa la condición elemento a elemento y selecciona uno de los dos valores.  
Es más eficiente que iterar con un `for`.

In [26]:
notas = np.array([4.5, 7.0, 6.0, 8.5, 5.9, 9.1, 3.2])
estado = np.where(notas >= 7.0, 'Aprobado', 'Reprobado')
print('Notas: ', notas)
print('Estado:', estado)

Notas:  [4.5 7.  6.  8.5 5.9 9.1 3.2]
Estado: ['Reprobado' 'Aprobado' 'Reprobado' 'Aprobado' 'Reprobado' 'Aprobado'
 'Reprobado']


In [27]:
# EJERCICIO 13
# Precios dinámicos: si stock < 20, aplicar precio especial (mayor).

stock           = np.array([50, 15, 8, 100, 18, 45, 3])
precio_normal   = np.full(7, 10.0)
precio_especial = np.full(7, 14.0)

# Selecciona el precio correcto según el stock
precio_final = np.where(stock < 20, precio_especial, precio_normal)

print('Stock:        ', stock)
print('Precio final: ', precio_final)

Stock:         [ 50  15   8 100  18  45   3]
Precio final:  [10. 14. 14. 10. 14. 10. 14.]


### `np.any`, `np.all`, `np.allclose`, `np.count_nonzero`

| Función | Pregunta |
|---|---|
| `np.any(cond)` | ¿hay al menos un True? |
| `np.all(cond)` | ¿son todos True? |
| `np.allclose(a, b)` | ¿son todos aproximadamente iguales? |
| `np.count_nonzero(a)` | ¿cuántos elementos son distintos de cero? |

In [28]:
stock = np.array([0, 5, 12, 0, 30, 0, 8])
print('¿Algún producto sin stock?  ', np.any(stock == 0))
print('¿Todos con stock?           ', np.all(stock > 0))
print('Productos disponibles:      ', np.count_nonzero(stock))

# allclose: para comparar resultados de cálculos numéricos (tolerancia de error)
a = np.array([1.0000001, 2.0000002])
b = np.array([1.0,       2.0      ])
print('¿Aprox iguales?             ', np.allclose(a, b))

¿Algún producto sin stock?   True
¿Todos con stock?            False
Productos disponibles:       4
¿Aprox iguales?              True


In [29]:
# EJERCICIO 14
# Validación de lecturas de sensores (rango válido: 1.0 a 100.0)

lecturas = np.array([36.5, 0.0, 45.2, 102.3, 38.1, 37.9, 0.0, 41.0])

# 14a. ¿Hay alguna lectura inválida (== 0 o > 100)?
hay_fallas = np.any(lecturas == 0)
print('¿Hay lecturas inválidas?', hay_fallas)

# 14b. ¿Todas las lecturas están en rango?
todas_ok = np.all((lecturas > 1) & (lecturas < 100))
print('¿Todas válidas?         ', todas_ok)

# 14c. Cuántos sensores reportaron cero
n_ceros = np.count_nonzero(lecturas == 0)
print('Sensores en cero:       ', n_ceros)

# 14d. Verifica que el promedio de dos métodos de cálculo son aprox iguales
validas = lecturas[(lecturas > 0) & (lecturas <= 100)]
media_a = np.mean(validas)
media_b = np.sum(validas) / len(validas)
print('¿Medias son iguales (allclose)?', np.allclose(media_a, media_b))

¿Hay lecturas inválidas? True
¿Todas válidas?          False
Sensores en cero:        2
¿Medias son iguales (allclose)? True


---
## Datos faltantes y estadística robusta
Los datos reales siempre tienen valores faltantes representados como `NaN`.  
Las funciones estándar son **contagiadas** por NaN — usan las versiones `nan-safe`.

### `np.isnan`, `np.nanmean`, `np.nansum`, `np.nanstd`, `np.nanmin`, `np.nanmax`, `np.var`

El NaN es contagioso: `5 + NaN = NaN`.  
Las funciones `nan*` excluyen los NaN antes de calcular.

| Función | Propósito |
|---|---|
| `np.isnan(x)` | detecta posiciones NaN (devuelve máscara booleana) |
| `np.nanmean` / `np.nansum` / `np.nanstd` | estadísticas ignorando NaN |
| `np.nanmin` / `np.nanmax` | mín/máx ignorando NaN |
| `np.var(x)` | varianza (dispersión alrededor de la media) |

In [30]:
datos = np.array([10.0, np.nan, 8.0, 9.5, np.nan, 7.0])
print('datos:', datos)
print('np.mean (contagiado): ', np.mean(datos))
print('np.nanmean (seguro):  ', np.nanmean(datos))

print('\nMáscara NaN:   ', np.isnan(datos))
print('Posiciones NaN:', np.where(np.isnan(datos))[0])

ventas = np.array([520.0, np.nan, 480.0, 610.0, np.nan, 495.0, 530.0])
print('\nEstadísticas nan-safe:')
print(f'  suma={np.nansum(ventas):.0f}  media={np.nanmean(ventas):.2f}  std={np.nanstd(ventas):.2f}')
print(f'  min={np.nanmin(ventas):.0f}   max={np.nanmax(ventas):.0f}')

# np.var
grupo_A = np.array([48, 50, 51, 49, 52])
grupo_B = np.array([20, 35, 50, 65, 80])
print(f'\nvar A={np.var(grupo_A):.2f}  var B={np.var(grupo_B):.2f}  (misma media, distinta dispersión)')

datos: [10.   nan  8.   9.5  nan  7. ]
np.mean (contagiado):  nan
np.nanmean (seguro):   8.625

Máscara NaN:    [False  True False False  True False]
Posiciones NaN: [1 4]

Estadísticas nan-safe:
  suma=2635  media=527.00  std=45.12
  min=480   max=610

var A=2.00  var B=450.00  (misma media, distinta dispersión)


In [31]:
# EJERCICIO 15
# Registro de temperaturas: 7 días x 3 sensores. Algunos fallaron (NaN).

temp = np.array([
    [22.1, np.nan, 21.8],
    [23.0, 22.5,   np.nan],
    [np.nan, 23.1, 22.9],
    [21.5, 22.0,   21.3],
    [24.1, np.nan, 23.8],
    [22.8, 22.1,   22.5],
    [21.0, 21.5,   np.nan]
])

# 15a. Total de lecturas faltantes
total_nan = np.sum(np.isnan(temp))
print('Lecturas faltantes:', total_nan)

# 15b. Temperatura promedio del periodo
prom = np.nanmean(temp)
print(f'Temperatura promedio: {prom:.2f} °C')

# 15c. Temperatura mínima y máxima del periodo
t_min = np.nanmin(temp)
t_max = np.nanmax(temp)
print(f'Rango: {t_min:.1f} — {t_max:.1f} °C')

# 15d. Varianza de las temperaturas válidas
temp_validas = temp[~np.isnan(temp)]
var = np.var(temp_validas)
print(f'Varianza: {var:.4f}')

Lecturas faltantes: 5
Temperatura promedio: 22.38 °C
Rango: 21.0 — 24.1 °C
Varianza: 0.7256


---
##  Construcción y manipulación de arrays
Métodos para crear arrays con patrones específicos, modificar su contenido  
y generar datos de prueba con distintas distribuciones.

### `np.full`, `np.empty`, `np.zeros_like`, `np.ones_like`

| Función | Descripción |
|---|---|
| `np.full(shape, valor)` | array relleno con un valor constante |
| `np.empty(shape)` | reserva memoria sin inicializar (no usar como ceros) |
| `np.zeros_like(a)` | ceros con el mismo shape y dtype que `a` |
| `np.ones_like(a)` | unos con el mismo shape y dtype que `a` |

In [32]:
print('np.full((2,4), 9.99):')
print(np.full((2, 4), 9.99))

ref = np.array([[1.5, 2.3], [4.1, 0.8]])
print('\nnp.zeros_like(ref):')
print(np.zeros_like(ref))
print('np.ones_like(ref):')
print(np.ones_like(ref))

# empty: valores de memoria sin inicializar
buf = np.empty((2, 3))
print('\nnp.empty (valores sin inicializar):')
print(buf)

np.full((2,4), 9.99):
[[9.99 9.99 9.99 9.99]
 [9.99 9.99 9.99 9.99]]

np.zeros_like(ref):
[[0. 0.]
 [0. 0.]]
np.ones_like(ref):
[[1. 1.]
 [1. 1.]]

np.empty (valores sin inicializar):
[[10.   0.   8. ]
 [ 9.5  0.   7. ]]


In [33]:
# EJERCICIO 16
# Comparar ventas reales con un presupuesto fijo de 500 por celda.

ventas_reales = np.array([
    [480, 510, 490],
    [520, 495, 505],
    [475, 530, 488]
])

# 16a. Crea la matriz de presupuesto con valor 500 (np.full)
presupuesto = np.full((3, 3), 500)

diferencia = ventas_reales - presupuesto

# 16b. Crea una máscara de ceros y marca con 1 donde no se cumplió la meta
bajo_meta = np.zeros_like(ventas_reales)
bajo_meta[diferencia < 0] = 1

print('Diferencia vs presupuesto:')
print(diferencia)
print('\nBajo meta (1 = no cumplió):')
print(bajo_meta)

Diferencia vs presupuesto:
[[-20  10 -10]
 [ 20  -5   5]
 [-25  30 -12]]

Bajo meta (1 = no cumplió):
[[1 0 1]
 [0 1 0]
 [1 0 1]]


### `np.append`, `np.insert`, `np.delete`, `np.unique`

Todas devuelven un **nuevo array** — NumPy no modifica arrays en lugar.

| Función | Descripción |
|---|---|
| `np.append(arr, values)` | agrega al final |
| `np.insert(arr, idx, values)` | inserta en una posición |
| `np.delete(arr, idx)` | elimina por índice |
| `np.unique(arr)` | valores únicos ordenados |

In [34]:
arr = np.array([10, 20, 30, 40, 50])
print('original:           ', arr)
print('append 60:          ', np.append(arr, 60))
print('insert 25 en pos 2: ', np.insert(arr, 2, 25))
print('delete pos 1:       ', np.delete(arr, 1))

cats = np.array(['A', 'B', 'A', 'C', 'B', 'A', 'D'])
vals, counts = np.unique(cats, return_counts=True)
print('\nUnique + conteo:')
for v, c in zip(vals, counts):
    print(f'  {v}: {c} veces')

original:            [10 20 30 40 50]
append 60:           [10 20 30 40 50 60]
insert 25 en pos 2:  [10 20 25 30 40 50]
delete pos 1:        [10 30 40 50]

Unique + conteo:
  A: 3 veces
  B: 2 veces
  C: 1 veces
  D: 1 veces


In [35]:
# EJERCICIO 17
# Gestión del registro de IDs de productos.

ids = np.array([101, 102, 104, 105, 107])
print('IDs iniciales:', ids)

# 17a. El producto 103 fue omitido. Insértalo en el índice 2.
ids = np.insert(ids, 2, 103)
print('Después de insertar 103:', ids)

# 17b. El producto 107 fue descontinuado. Elimínalo (está al final).
ids = np.delete(ids, -1)
print('Después de eliminar 107:', ids)

# 17c. Llegó un lote con IDs [108, 109, 110]. Agrégalo al final.
ids = np.append(ids, [108, 109, 110])
print('Después de agregar lote:', ids)

# 17d. El sistema tiene duplicados. Obtén los IDs únicos.
ids_dup = np.append(ids, [103, 108, 101])
ids_unicos = np.unique(ids_dup)
print('IDs únicos:', ids_unicos)

IDs iniciales: [101 102 104 105 107]
Después de insertar 103: [101 102 103 104 105 107]
Después de eliminar 107: [101 102 103 104 105]
Después de agregar lote: [101 102 103 104 105 108 109 110]
IDs únicos: [101 102 103 104 105 108 109 110]


### `np.random.uniform`, `np.random.randn`, `np.random.choice`

| Función | Distribución | Cuándo usarla |
|---|---|---|
| `uniform(low, high, size)` | Uniforme continua | valores entre dos límites con igual probabilidad |
| `randn(shape)` | Normal estándar (μ=0, σ=1) | datos con distribución gaussiana |
| `choice(arr, size, replace)` | Muestreo | seleccionar elementos de un conjunto |

Para obtener una normal con μ y σ propios: `μ + σ * np.random.randn(n)`

In [36]:
np.random.seed(7)

# uniform
print('uniform [5, 50]:', np.round(np.random.uniform(5, 50, 5), 2))

# randn -> transformar a distribución real
alturas = 170 + 8 * np.random.randn(5)
print('alturas (μ=170, σ=8):', np.round(alturas, 1))

# choice
ciudades = np.array(['Quito', 'Guayaquil', 'Cuenca', 'Ambato'])
print('muestreo:', np.random.choice(ciudades, size=6, replace=True))

uniform [5, 50]: [ 8.43 40.1  24.73 37.56 49.01]
alturas (μ=170, σ=8): [170.7 195.6 168.7 167.7 186.2]
muestreo: ['Ambato' 'Ambato' 'Quito' 'Quito' 'Ambato' 'Ambato']


In [37]:
# EJERCICIO 18
# Dataset sintético de 30 clientes.

np.random.seed(42)
n = 30

# 18a. Edades entre 18 y 65 (uniform, convertir a int)
edades = (np.random.uniform(18, 65, 30)).astype(int)

# 18b. Ingresos: media 800 USD, std 200 USD (randn)
ingresos = np.random.randn(30) * 200 + 800
ingresos = np.round(np.maximum(ingresos, 200), 2)  # mínimo 200

# 18c. Ciudad asignada por muestreo con reemplazo (choice)
ciudades = np.array(['Quito', 'Guayaquil', 'Cuenca', 'Ambato', 'Loja'])
ciudad_cliente = np.random.choice(ciudades, size=n, replace=True)

print('Primeros 5 clientes:')
print(f'{"Edad":>5}  {"Ingreso":>10}  Ciudad')
print('-' * 30)
for i in range(5):
    print(f'{edades[i]:>5}  {ingresos[i]:>10.2f}  {ciudad_cliente[i]}')

print(f'\nIngreso promedio: USD {np.mean(ingresos):.2f}')
print(f'Ciudades únicas: {np.unique(ciudad_cliente)}')

Primeros 5 clientes:
 Edad     Ingreso  Ciudad
------------------------------
   35      569.80  Quito
   62      875.14  Cuenca
   52      679.87  Loja
   46      741.66  Guayaquil
   25      679.66  Guayaquil

Ingreso promedio: USD 763.59
Ciudades únicas: ['Ambato' 'Cuenca' 'Guayaquil' 'Loja' 'Quito']


---
##  Persistencia: guardar y cargar arrays
Después de procesar datos, necesitamos guardarlos para reutilizarlos.  
- **`.npy`** (binario): rápido, exacto, solo NumPy.
- **`genfromtxt`** (texto): portable, legible por cualquier herramienta.

### `np.save` y `np.load` — formato binario `.npy`

Guarda el array con toda su precisión. Mucho más rápido que CSV  
para arrays grandes porque no convierte a texto.

In [38]:
np.random.seed(1)
resultado = np.random.rand(5, 3)

np.save('resultado.npy', resultado)
print('Guardado. Tamaño en disco:', os.path.getsize('resultado.npy'), 'bytes')

cargado = np.load('resultado.npy')
print('¿Idéntico al original?', np.allclose(resultado, cargado))

Guardado. Tamaño en disco: 248 bytes
¿Idéntico al original? True


### `np.genfromtxt` — leer archivos CSV con valores faltantes

Más robusto que `loadtxt`: maneja celdas vacías, tipos mixtos y cabeceras.

```python
np.genfromtxt('archivo.csv', delimiter=',', skip_header=1, filling_values=np.nan)
```

In [39]:
# Creamos un CSV con valores faltantes para la demo
csv = """id,precio,stock
1,2.50,100
2,3.75,
3,1.20,200
4,,150
5,4.00,80
"""
with open('inventario.csv', 'w') as f:
    f.write(csv)

datos = np.genfromtxt('inventario.csv', delimiter=',',
                       skip_header=1, filling_values=np.nan)
print('Datos cargados:')
print(datos)
print('Faltantes por columna:', np.sum(np.isnan(datos), axis=0))

Datos cargados:
[[  1.     2.5  100.  ]
 [  2.     3.75    nan]
 [  3.     1.2  200.  ]
 [  4.      nan 150.  ]
 [  5.     4.    80.  ]]
Faltantes por columna: [0 1 1]


In [40]:
# EJERCICIO 19 — Persistencia completa
# 1. Cargar CSV con faltantes
# 2. Imputar NaN con el promedio de la columna
# 3. Guardar limpio en .npy
# 4. Cargar y verificar

ventas_csv = """dia,norte,sur,centro
1,520,480,
2,,495,510
3,505,510,498
4,490,,520
5,530,488,505
"""
with open('ventas.csv', 'w') as f:
    f.write(ventas_csv)

# 19a. Carga ventas.csv
ventas = np.genfromtxt('ventas.csv', delimiter=',',skip_header=1, filling_values=np.nan)
print('Datos cargados:')
print(ventas)

# 19b. Imputa NaN con el promedio de cada columna de ventas (cols 1,2,3)
ventas_ok = ventas.copy()
for col in range(1, 4):
    columna = ventas[:, col]
    prom = np.nanmean(columna)
    ventas_ok[:, col] = np.where(np.isnan(columna), prom, columna)

print('\nDatos imputados:')
print(np.round(ventas_ok, 1))

# 19c. Guarda en ventas_ok.npy
np.save('ventas_ok.npy', ventas_ok)

# 19d. Carga y verifica que no hay NaN
check = np.load('ventas_ok.npy')
print('¿Quedan NaN?', np.any(np.isnan(check)))

Datos cargados:
[[  1. 520. 480.  nan]
 [  2.  nan 495. 510.]
 [  3. 505. 510. 498.]
 [  4. 490.  nan 520.]
 [  5. 530. 488. 505.]]

Datos imputados:
[[  1.  520.  480.  508.2]
 [  2.  511.2 495.  510. ]
 [  3.  505.  510.  498. ]
 [  4.  490.  493.2 520. ]
 [  5.  530.  488.  505. ]]
¿Quedan NaN? False


---
## Lista de verificación antes de entregar

- [ ] `Kernel > Restart & Run All` sin errores
- [ ] Todos los `# TU CODIGO AQUI` reemplazados
- [ ] Celdas Markdown intactas
- [ ] Nombre del archivo: `deber_numpy_<tu_nombre>.ipynb`

---

**Resumen de los 61 métodos cubiertos**

| Unidad | Métodos |
|---|---|
| U1 — Fundamentos | `array` `zeros` `ones` `eye` `arange` `linspace` `seed` `rand` `randint` `reshape` `flatten` `sum` `mean` `median` `std` `min` `max` `dot` `multiply` `concatenate` |
| U2 — Estructura | `ravel` `transpose` `astype` `copy` |
| U3 — Matemática | `sqrt` `exp` `log` `power` `round` `floor` `ceil` `trunc` `greater` `equal` `maximum` `minimum` |
| U4 — Filtrado | `where` `any` `all` `allclose` `count_nonzero` |
| U5 — NaN | `isnan` `nanmean` `nansum` `nanstd` `nanmin` `nanmax` `var` |
| U6 — Manipulación | `full` `empty` `zeros_like` `ones_like` `append` `insert` `delete` `unique` `uniform` `randn` `choice` |
| U7 — Persistencia | `save` `load` `genfromtxt` |