<div style='background: linear-gradient(105deg, #0D2B4E 0%, #1A3A5C 60%, #2A5A8C 100%); padding: 40px 36px; border-radius: 10px; color: white; margin-bottom: 8px;'>
<h1 style='color: #CC0000; font-size: 2.2em; margin: 0 0 8px 0;'>Análisis de Datos — TDSD353</h1>
<h2 style='color: #A8C4DC; font-size: 1.3em; margin: 0 0 16px 0; font-weight: 400;'>Capítulo 1: Introducción · Semana 1 · Período 2026-A</h2>
<p style='color: #6A8FAA; margin: 0; font-size: 0.95em;'>Docente: Juan Carlos Gonzalez Ortiz &nbsp;·&nbsp; ESFOT — EPN &nbsp;·&nbsp; GR2 · Martes 10:00–13:00</p>
</div>



---

<div style='background: linear-gradient(105deg, #0D2B4E 0%, #1A3A5C 100%); padding: 28px 32px; border-radius: 10px; color: white; border-left: 6px solid #CC0000;'>
<h1 style='color: #CC0000; margin: 0 0 8px 0; font-size: 1.8em;'>TALLER AUTÓNOMO 1</h1>
<h2 style='color: #A8C4DC; margin: 0 0 12px 0; font-weight: 400; font-size: 1.1em;'>Trabajo individual en laboratorio</h2>

</div>

---

## 📋 Instrucciones generales

1. **Completa cada celda de código** en orden, sin saltarte ninguna.
2. **Agrega tu nombre y fecha** en la celda de la Parte 0.
3. **No borres** los comentarios de guía — son parte de la evaluación.
4. **Ejecuta cada celda** y verifica que no haya errores antes de continuar.
5. **Agrega una celda Markdown** al final con tus conclusiones personales.

---

## Parte 0 — Identificación

> **✏️ Modifica la celda de abajo con tus datos antes de continuar.**

In [6]:
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# PARTE 0 — IDENTIFICACIÓN DEL ESTUDIANTE
# Modifica los valores entre comillas con tus datos
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

nombre_estudiante = "ALAN REYES"
fecha_entrega     = "2026-04-07"
grupo             = "GR2"

print("=" * 50)
print(f"  Estudiante: {nombre_estudiante}")
print(f"  Fecha:      {fecha_entrega}")
print(f"  Grupo:      {grupo}")
print(f"  Asignatura: Análisis de Datos — TDSD353")
print(f"  Semana:     1 — Taller Autónomo")
print("=" * 50)

  Estudiante: ALAN REYES
  Fecha:      2026-04-07
  Grupo:      GR2
  Asignatura: Análisis de Datos — TDSD353
  Semana:     1 — Taller Autónomo


---
## Parte 1 — Configuración del entorno

**Objetivo:** verificar que NumPy está instalado correctamente y entender su estructura básica.

In [7]:
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# PARTE 1.1 — Importar NumPy y verificar versión
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

import numpy as np

# TODO: Imprime la versión de NumPy instalada
# Pista: usa np.__version__

# TU CÓDIGO AQUÍ
print("NumPy versión:", np.__version__)  # reemplaza ... con el atributo correcto

# Verifica también la versión de Python
import sys
print("Python versión:", sys.version[:6])

NumPy versión: 2.4.2
Python versión: 3.13.1


---
## Parte 2 — Arrays 1D y 2D

**Objetivo:** crear arrays con diferentes métodos y explorar sus propiedades.


In [8]:
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# PARTE 2.1 — Crear un array 1D con precios reales
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# TODO: Crea un array 1D con los precios de compra
# de al menos 6 productos de papelería que conozcas
# Ejemplo: cuaderno, lápiz, borrador, regla, tijeras, pegamento

precios_compra = np.array([1.05, 0.15, 0.25, 0.3, 0.75, 1])  # reemplaza ... con tus valores

print("Precios de compra:")
print(precios_compra)

print(f"Shape: {precios_compra.shape}")
print(f"ndim: {precios_compra.ndim}")
print(f"dtype: {precios_compra.dtype}")

# TODO: Imprime el shape, ndim y dtype del array


Precios de compra:
[1.05 0.15 0.25 0.3  0.75 1.  ]
Shape: (6,)
ndim: 1
dtype: float64


In [9]:
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# PARTE 2.2 — Crear matrices con np.ones y np.zeros
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# TODO: Crea una matriz de 4×4 llena de unos
matriz_unos = np.ones([4,4])  # usa np.ones con dimensión (4, 4)

# TODO: Crea una matriz de 4×4 llena de ceros
matriz_ceros = np.zeros([4,4])  # usa np.zeros con dimensión (4, 4)

print("Matriz de unos (4×4):")
print(matriz_unos)
print()
print("Matriz de ceros (4×4):")
print(matriz_ceros)
print()

# TODO: ¿Cuál es el dtype por defecto de np.ones y np.zeros?
# Escribe tu respuesta en un print()
print(f"dtype de np.ones:  {matriz_unos.dtype}")
print(f"dtype de np.zeros: {matriz_ceros.dtype}")
print("→ es de tipo float64")# Escribe tu respuesta en un print()
print("¿Por qué son float64 en lugar de int?")
print("→ float64 es el tipo estándar para operaciones con NumPy, evita la pérdida de precisión")# Escribe tu respuesta en un print()

Matriz de unos (4×4):
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Matriz de ceros (4×4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

dtype de np.ones:  float64
dtype de np.zeros: float64
→ es de tipo float64
¿Por qué son float64 en lugar de int?
→ float64 es el tipo estándar para operaciones con NumPy, evita la pérdida de precisión


In [10]:
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# PARTE 2.3 — Matrices con valores aleatorios
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# TODO: Crea una matriz 5×5 con enteros aleatorios del 1 al 10
M1 = np.random.randint(1, 11, size=(5,5))  # usa np.random.randint

# TODO: Crea otra matriz 5×5 con enteros aleatorios del 1 al 10
M2 = np.random.randint(1, 11, size=(5,5))  # diferente a M1

print("M1 (5×5 aleatoria):")
print(M1)
print()
print("M2 (5×5 aleatoria):")
print(M2)
print()





M1 (5×5 aleatoria):
[[ 6  2  9  9  5]
 [ 9  9  3  5  7]
 [ 7  3  3  4  3]
 [10  8  8  4  4]
 [ 3  3  7  1  7]]

M2 (5×5 aleatoria):
[[ 8  7  3 10  8]
 [10  9  6  8  2]
 [ 2  1  9  6  3]
 [ 1  9 10  5  5]
 [ 5  1  4  9 10]]



---
## Parte 3 — Indexación y Bordes


In [11]:
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# PARTE 3.1 — Explorar la indexación de M1
# (usa la M1 que creaste en la Parte 2.3)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

print("Usando la matriz M1:")
print(M1)
print()

# TODO: Extrae e imprime cada uno de los siguientes datos
print("Primera fila:")
print(M1[0,:]) #Completa 

print("Última fila:")
print(M1[-1,:]) #Completa 

print("Primera columna:")
print(M1[:,0])  #Completa 

print("Última columna:")
print(M1[:,-1])  #Completa 

print("Submatriz interior (filas 1:4, cols 1:4):")
print(M1[1:4,1:4])  #Completa 

Usando la matriz M1:
[[ 6  2  9  9  5]
 [ 9  9  3  5  7]
 [ 7  3  3  4  3]
 [10  8  8  4  4]
 [ 3  3  7  1  7]]

Primera fila:
[6 2 9 9 5]
Última fila:
[3 3 7 1 7]
Primera columna:
[ 6  9  7 10  3]
Última columna:
[5 7 3 4 7]
Submatriz interior (filas 1:4, cols 1:4):
[[9 3 5]
 [3 3 4]
 [8 8 4]]


---

<div style='background: #F0F4F8; padding: 20px 28px; border-radius: 8px; border-left: 5px solid #0D2B4E; margin-top: 16px;'>
<h3 style='color: #0D2B4E; margin: 0 0 10px 0;'>✅ Checklist de entrega</h3>
<p style='color: #1A3A5C; margin: 0; font-size: 0.95em;'>
Antes de guardar y entregar tu notebook, verifica:
</p>
<ul style='color: #1A3A5C; font-size: 0.9em; margin: 8px 0 0 0;'>
<li>☐ Nombre y fecha completados en la <b>Parte 0</b></li>
<li>☐ Todas las celdas ejecutadas sin errores</li>
<li>☐ Archivo <code>resultado_taller_APELLIDO.txt</code> generado correctamente</li>
<li>☐ Nombre del archivo del notebook: <code>semana1_APELLIDO.ipynb</code></li>
</ul>
</div>

---

<div style='background: linear-gradient(105deg, #0D2B4E, #1A3A5C); padding: 20px 28px; border-radius: 8px; color: white; text-align: center; margin-top: 8px;'>
<p style='margin: 0; font-size: 0.9em; color: #A8C4DC;'>Análisis de Datos — TDSD353 &nbsp;·&nbsp; ESFOT — EPN &nbsp;·&nbsp; Período 2026-A</p>
<p style='margin: 4px 0 0 0; font-size: 0.85em; color: #6A8FAA;'>Docente: Juan Carlos Gonzalez Ortiz</p>
</div>