### Clase 2 de NumPy 


## Importación de NumPy
Siempre importamos NumPy con el alias `np` por convención.

In [1]:
import numpy as np
print(f'Versión de NumPy: {np.__version__}')

Versión de NumPy: 2.3.5


---
## Creación de Arrays


### `np.zeros()`, `np.ones()`, `np.full()` — Arrays con valores predefinidos

- `np.zeros()`: crea un arreglo lleno de ceros.
- `np.ones()`: crea un arreglo lleno de unos.
- `np.full()`: crea un arreglo lleno con un valor específico.

In [11]:
display("Matriz de zeros:", np.zeros(5))
display("Matriz de ones:", np.ones((2, 3)))
display("Matriz de full:", np.full((2, 3), 7))

'Matriz de zeros:'

array([0., 0., 0., 0., 0.])

'Matriz de ones:'

array([[1., 1., 1.],
       [1., 1., 1.]])

'Matriz de full:'

array([[7, 7, 7],
       [7, 7, 7]])

### `np.arange()` y `np.linspace()` — Secuencias numéricas

`np.arange(inicio, fin, paso)`
- Genera valores con un **paso fijo**.
- El valor final (`fin`) normalmente es **exclusivo** (no se incluye).
- Es ideal cuando te interesa controlar el incremento entre elementos.

`np.linspace(inicio, fin, num)`
- Genera una secuencia con una **cantidad fija de elementos** (`num`).
- Incluye el valor (`fin`) por defecto 
- Es ideal cuando necesitas repartir puntos de forma uniforme en un intervalo.

In [18]:
# arange: inicio, fin (exclusivo), paso
print("Arage: ", np.arange(0, 10, 2))

# linspace: inicio, fin (inclusivo), cantidad de elementos
print("Linspace: ", np.linspace(0, 10, 5))


Arage:  [0 2 4 6 8]
Linspace:  [ 0.   2.5  5.   7.5 10. ]


### `np.eye()` — Matriz identidad

Una matriz identidad es un tipo especial de matriz cuadrada (mismo número de filas y columnas) en la que todos los elementos de la diagonal principal son 1 y el resto son 0.


In [ ]:
print("Matriz identidad:\n", np.eye(3)*9) #*9 hace que los 1 sean 9

Matriz identidad:
 [[9. 0. 0.]
 [0. 9. 0.]
 [0. 0. 9.]]


### `np.random` — Arrays aleatorios

In [36]:
np.random.seed(5)
#Genera 5 números decimales aleatorios con distribución uniforme entre 0 y 1
print(np.round(np.random.rand(5), 2))
#Crea 5 enteros aleatorios entre 1 y 99.
print(np.random.randint(1, 100, size=5))
#Elige 3 elementos aleatorios de una lista.
print(np.random.choice([10, 20, 30, 40], size=3))

[0.22 0.87 0.21 0.92 0.49]
[63 28 31 81  8]
[10 40 20]


---
## Forma y Estructura de Arrays
### Atributos: `shape: (filas, columnas)`, `ndim:dimensiones`, `size:total de elementos`, `dtype:tipo de dato`

In [51]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
display(arr)
print("shape:", arr.shape)
print("ndim:", arr.ndim)
print("size (tamaño):", arr.size)
print("dtype (tipo de dato):", arr.dtype)

array([[1, 2, 3],
       [4, 5, 6]])

shape: (2, 3)
ndim: 2
size (tamaño): 6
dtype (tipo de dato): int64


### `reshape()` — Cambiar la forma  
El total de elementos debe coincidir.
12 elementos se puede convertir a (3,4), (2,6), (4,3), etc.  
No se puede a (5,3) porque 
5×3 = 15


In [53]:
arr = np.arange(12)
print("Original: ", arr)
print("Reshape (3, 4):\n", arr.reshape(3, 4))
print("Reshape (6, 2):\n", arr.reshape(6, 2))

Original:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshape (3, 4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshape (6, 2):
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


### `flatten()` y `ravel()` — Aplanar arrays
flatten (copia)
ravel (vista)

In [60]:
mat = np.array([[1, 2], [3, 4]])
print('Original\n', mat)
print("Flatten (copia):", mat.flatten())
print("Ravel (vista):", mat.ravel())

Original
 [[1 2]
 [3 4]]
Flatten (copia): [1 2 3 4]
Ravel (vista): [1 2 3 4]


### `transpose()` / `.T` — Transponer

In [65]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
print('Original\n', mat)
print("Transpuesta\n", mat.T)

Original
 [[1 2 3]
 [4 5 6]]
Transpuesta
 [[1 4]
 [2 5]
 [3 6]]


### `astype()` — Cambiar tipo de dato

Numéricas básicas

int → float (ej. arr.astype(float))

float → int (ej. arr.astype(int), que trunca decimales)

int32 ↔ int64 (dependiendo de la arquitectura o necesidad de precisión)

float32 ↔ float64 (para cálculos más precisos o más ligeros)

Booleanos

int → bool (0 se convierte en False, cualquier otro valor en True)

bool → int (False → 0, True → 1)

Strings

int/float → str (ej. arr.astype(str))

str → int/float (si las cadenas representan números válidos)

Tipos especiales

complex ↔ float/int (aunque al convertir de complejo a real se pierde la parte imaginaria)

datetime64 

In [72]:
enteros = np.array([1, 2, 3])
flotantes = enteros.astype(np.float64)
cadena = enteros.astype(str)

print(enteros, enteros.dtype)
print(flotantes, flotantes.dtype)
print(cadena, cadena.dtype)


[1 2 3] int64
[1. 2. 3.] float64
['1' '2' '3'] <U21


---
## Indexación y Segmentación
### Indexación básica (1D y 2D)

In [80]:
a = np.array([10, 20, 30, 40, 50])
print('Elemento 0:', a[0])
print('Último:', a[-1])

b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
display(b)
print('Fila 1, Col 2:', b[1, 2])
print('Fila 0:', b[0])

Elemento 0: 10
Último: 50


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Fila 1, Col 2: 6
Fila 0: [1 2 3]


### Slicing — Segmentación con `:`
[0 1 2 3 4 5 6 7 8 9]

En Python/NumPy, el slicing es:

`inicio:fin:paso`

In [90]:
a = np.arange(10) #esto es igual a poner np.arange(inicio=0, fin=10, paso =1)
print('Original:', a)
print('Obtener los numeros 2-3-4-5-6 de la matriz', a[2:7])
print('Obtener todos los elementos de la fila con paso 2:', a[::2])

b = np.arange(12).reshape(3, 4)
print('\nMatriz:\n', b)
print('Filas 0-1, Cols 1-2:\n', b[0:2, 1:3])
print('Toda col 2:', b[:, 2])

Original: [0 1 2 3 4 5 6 7 8 9]
Obtener los numeros 2-3-4-5-6 de la matriz [2 3 4 5 6]
Obtener todos los elementos de la fila con paso 2: [0 2 4 6 8]

Matriz:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Filas 0-1, Cols 1-2:
 [[1 2]
 [5 6]]
Toda col 2: [ 2  6 10]


### Indexación booleana (máscaras)

In [95]:
arr = np.array([15, 22, 8, 33, 5, 42])
#Obtener los numeros del array mayores a 20
mascara = arr > 20
print("Mascara:", mascara)
print("De forma directa: arr[arr>20] ->", arr[arr>20])


Mascara: [False  True False  True False  True]
De forma directa: arr[arr>20] -> [22 33 42]


### `np.where()` — Condición con reemplazo

es un “if-else vectorizado” en NumPy.

In [100]:
arr = np.array([1, -2, 3, -4, 5])
print("Indices mayores a 0: ", np.where(arr > 0))
print("Reemplazo:", np.where(arr > 0, arr, 0))

Indices mayores a 0:  (array([0, 2, 4]),)
Reemplazo: [1 0 3 0 5]


### Operaciones con escalares (Broadcasting básico)

In [102]:
arr = np.array([1, 2, 3, 4])
print("arr*10:", arr*10)
print("arr+100:", arr+100)

arr*10: [10 20 30 40]
arr+100: [101 102 103 104]


---
## Funciones Universales — UFuncs
### Funciones matemáticas

In [113]:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Raiz cuadrada:", np.sqrt(a))
print("Suma:", np.add(a, b))
print("Resta:", np.subtract(b, a))
print("Multiplicación:", np.multiply(a, b))
print("División:", np.divide(a, b))
print("Potencia:", np.power(a, 2))

Raiz cuadrada: [1.         1.41421356 1.73205081]
Suma: [5 7 9]
Resta: [3 3 3]
Multiplicación: [ 4 10 18]
División: [0.25 0.4  0.5 ]
Potencia: [1 4 9]


### Funciones de redondeo

In [126]:
arr = np.array([1.23, 2.78, 3.45, 4.51])
#Round: Redondear valores numéricos de un arreglo a un número específico de decimales.
print("np.rpund:", np.round(arr, 1))
#Floor: Redondea hacia abajo (al entero menor).
print("np.floor:", np.floor(arr))
#Ceil: Redondea hacia arriba (al entero mayor).
print("np.ceil:", np.ceil(arr))
#Trunc: Corta la parte decimal
print("np.trunc:", np.trunc(arr))

np.rpund: [1.2 2.8 3.4 4.5]
np.floor: [1. 2. 3. 4.]
np.ceil: [2. 3. 4. 5.]
np.trunc: [1. 2. 3. 4.]


---
## Funciones de Agregación / Estadísticas
### Estadísticas básicas

In [128]:
arr = np.array([12, 15, 8, 22, 35, 10, 18])

print('np.sum:', np.sum(arr))
print('np.mean:', np.round(np.mean(arr), 5))
print('np.median:', np.median(arr))
print('np.std:', np.round(np.std(arr), 5))
print('np.min:', np.min(arr))
print('np.max:', np.max(arr))

np.sum: 120
np.mean: 17.14286
np.median: 15.0
np.std: 8.52607
np.min: 8
np.max: 35


### Agregaciones por eje

In [134]:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print('Suma total:', np.sum(mat))
print('Suma por columnas (axis=0):', np.sum(mat, axis=0))
print('Suma por filas (axis=1):', np.sum(mat, axis=1))
print('Media por columnas:', np.mean(mat, axis=0))

Suma total: 45
Suma por columnas (axis=0): [12 15 18]
Suma por filas (axis=1): [ 6 15 24]
Media por columnas: [4. 5. 6.]


---
## Manipulación de Arrays
### `np.concatenate()` — Unir arrays

In [137]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


# En 2D
m1 = np.array([[1, 2], 
               [3, 4]])
m2 = np.array([[5, 6], 
               [7, 8]])

print('concatenate axis=0:\n', np.concatenate([m1, m2], axis=0))
print('concatenate axis=1:\n', np.concatenate([m1, m2], axis=1))

concatenate axis=0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
concatenate axis=1:
 [[1 2 5 6]
 [3 4 7 8]]


### `np.append()`, `np.insert()`, `np.delete()`

In [141]:
arr = np.array([1, 2, 3, 4, 5])
print('append:', np.append(arr, [6, 7]))
print('insert:', np.insert(arr, 2, 99))
print('delete:', np.delete(arr, 2))

append: [1 2 3 4 5 6 7]
insert: [ 1  2 99  3  4  5]
delete: [1 2 4 5]


### `np.unique()` — Valores únicos

In [149]:
arr = np.array([3, 1, 2, 3, 1, 4, 2])
unicos, conteos = np.unique(arr, return_counts=True)
print('Elementos únicos:', unicos)
print('Conteo:', conteos)

Elementos únicos: [1 2 3 4]
Conteo: [2 2 2 1]


---
## Multiplicacion de vectores


### `np.dot()` y `np.multiply()` —
## En vectores
`np.multiply`
Realiza multiplicación elemento a elemento (Hadamard product).
Cada posición se multiplica con la correspondiente del otro vector.


In [151]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print('np.multiply:', np.multiply(a, b)) # -> 1*4 , 2*5 , 3*6

np.multiply: [ 4 10 18]


`dot` Calcula el producto escalar (inner product).Multiplica elemento a elemento y luego suma los resultados.



In [154]:
print('np.dot:',np.dot(a, b))  # -> 1*4 + 2*5 + 3*6

np.dot: 32


## En matrices

`np.multiply()` , sigue siendo elemento a elemento. Las dimensiones deben coincidir

In [157]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print('np.multiply:\n', np.multiply(A, B))

np.multiply:
 [[ 5 12]
 [21 32]]


`np.dot()`Realiza multiplicación matricial (álgebra lineal).Combina filas de la primera matriz con columnas de la segunda.
https://www.formulasexplicadas.com/multiplicacion-de-matrices/

In [160]:
print('np.dot:\n',np.dot(A, B))

np.dot:
 [[19 22]
 [43 50]]


---
## Copias vs Vistas
### Diferencia fundamental entre `copy()` y una vista

In [163]:
original = np.array([1, 2, 3, 4, 5])

# Vista: comparte memoria
vista = original[1:4]
vista[0] = 99
print('original (modificado por vista):', original)

# Copia: independiente
original2 = np.array([1, 2, 3, 4, 5])
copia = original2[1:4].copy()
copia[0] = 99
print('original2 (no modificado):', original2)
print('copia:', copia)

original (modificado por vista): [ 1 99  3  4  5]
original2 (no modificado): [1 2 3 4 5]
copia: [99  3  4]


---
## Funciones Útiles Adicionales
### `np.any()`, `np.all()` — Verificaciones lógicas

In [166]:
arr = np.array([1, 0, 3, 0, 5])

print('alguno > 3?', np.any(arr>3))
print('todos > 0?', np.all(arr>0))

alguno > 3? True
todos > 0? False



## Seccion 2: Tratamiento de Datos Faltantes con NumPy

La **limpieza de datos** es fundamental en cualquier análisis. En NumPy, los datos faltantes se representan como `np.nan` (_Not a Number_).

### 2.1 Crear y detectar valores NaN

Así es como se reserva un lugar para un elemento faltante en un array:


In [171]:
array = np.array([1, 2, np.nan, 4, 5])
array

array([ 1.,  2., nan,  4.,  5.])

Para detectar la presencia de `NaN` usamos `np.isnan()`:

In [172]:
np.isnan(array)

array([False, False,  True, False, False])

### 2.2 Cálculos con NaN

Las operaciones matemáticas estándar sobre arrays con `NaN` devuelven `NaN`:

In [175]:
np.mean(array) #devuelve nan porque en el arreglo hay un dato faltante (NaN)

np.float64(nan)

NumPy ofrece variantes de sus funciones que **ignoran los NaN** automáticamente:

In [179]:
np.nanmean(array)

np.float64(3.0)

In [183]:
print('suma sin NaN:', np.nansum(array))
print('mínimo sin NaN:', np.nanmin(array))
print('máximo sin NaN:', np.nanmax(array))
print('mediana sin NaN:', np.nanmedian(array))



suma sin NaN: 12.0
mínimo sin NaN: 1.0
máximo sin NaN: 5.0
mediana sin NaN: 3.0


### 2.3 Reemplazar valores NaN

Una estrategia común es sustituir `NaN` por otro valor usando `np.where()`, que funciona como un bucle condicional: _"donde se cumpla esta condición, haz X; donde no, haz Y"_.

**Reemplazar NaN por cero:**


In [ ]:
display(array)
array_con_0 = np.where(np.isnan(array), 0, array)
array_con_0

[ 1.  2. nan  4.  5.]


array([1., 2., 0., 4., 5.])

**Reemplazar NaN por el promedio del array:**

In [190]:
display(array)
promedio = np.nanmean(array)
array_con_promedio = np.where(np.isnan(array), promedio, array)
array_con_promedio

array([ 1.,  2., nan,  4.,  5.])

array([1., 2., 3., 4., 5.])

### 2.4 Eliminar valores NaN

Otra estrategia es filtrar el array para **eliminar** los `NaN`. Usando `~` (tilde, que actúa como negación lógica) podemos conservar solo los valores válidos:

In [191]:
# eliminar solo los NaN
array[np.isnan(array)]

array([nan])

In [193]:
# sólo  los valores válidos
array_filtrado = array[~np.isnan(array)]
array_filtrado

array([1., 2., 4., 5.])

> **Conclusión:** NumPy ofrece herramientas suficientes para identificar, manejar y sustituir valores `NaN`, lo que permite mantener la integridad de los análisis.

---

## SECCIÓN 3 — Importación y Exportación de Datos con NumPy

En esta sección aprenderemos a **importar datos desde archivos externos** para cargarlos en arrays, y el proceso inverso: **exportar arrays hacia archivos CSV**.

### 3.1 Importar datos con `genfromtxt()`

`genfromtxt()` es el método de NumPy para leer archivos de texto.Tiene particularidades importantes porque los arrays solo admiten **un tipo de dato** a la vez.

Si intentas leerlo sin parámetros adicionales, probablemente obtengas errores. Los parámetros esenciales son:

| Parámetro        | Descripción                                            |
| ---------------- | ------------------------------------------------------ |
| `delimiter`      | Caracter separador de columnas (ej: `','`)             |
| `skip_header`    | Número de filas iniciales a omitir (encabezados)       |
| `filling_values` | Valor con el que rellenar los datos faltantes          |
| `dtype`          | Tipo de dato del array resultante (ej: `int`, `float`) |

#### Paso 1 — Intentar leer el archivo sin configurar parámetros

Usaremos el archivo `medallas.csv`, que contiene el medallero olímpico. Si intentamos leerlo directamente, obtendremos un error porque el archivo tiene **texto y números mezclados**, y `genfromtxt()` necesita que le indiquemos cómo manejarlos.

In [194]:
# generar un error
ruta = 'medallas.csv'
array_error = np.genfromtxt(ruta)
array_error

ValueError: Some errors were detected !
    Line #15 (got 2 columns instead of 1)
    Line #17 (got 2 columns instead of 1)
    Line #20 (got 2 columns instead of 1)
    Line #22 (got 2 columns instead of 1)
    Line #24 (got 2 columns instead of 1)
    Line #27 (got 4 columns instead of 1)
    Line #36 (got 2 columns instead of 1)
    Line #39 (got 3 columns instead of 1)
    Line #44 (got 4 columns instead of 1)
    Line #63 (got 2 columns instead of 1)
    Line #65 (got 2 columns instead of 1)
    Line #70 (got 2 columns instead of 1)
    Line #72 (got 3 columns instead of 1)
    Line #73 (got 3 columns instead of 1)
    Line #74 (got 4 columns instead of 1)
    Line #77 (got 2 columns instead of 1)
    Line #78 (got 2 columns instead of 1)
    Line #82 (got 2 columns instead of 1)
    Line #86 (got 3 columns instead of 1)

#### Paso 2 — Leer solo las columnas numéricas

Como los arrays solo admiten un tipo de dato, debemos **omitir la columna de texto** (País) y configurar correctamente los parámetros:


In [200]:
ruta = 'medallas.csv'

array_medallas = np.genfromtxt(
    ruta,
    delimiter=',', # separador de columnas
    filling_values=0, # las celdas vacías se rellenan con 0
    skip_header=1, # omitir primera fila de títulos o encabezados
    dtype=int, #convertir los datos a enteros
    usecols=(0,1,2,3) # uso solo columnas numericas
)

print(f'La forma del array es: {array_medallas.shape}')
print(f'Primeras 5 filas (oro, plata, bronce, total):\n {array_medallas[:5]}')


La forma del array es: (93, 4)
Primeras 5 filas (oro, plata, bronce, total):
 [[ 0  1  2  3]
 [ 0  2  2  4]
 [17  7 22 46]
 [ 1  1  5  7]
 [ 0  3  4  7]]


Otra opcion seria sustituir los valores faltantes, por la media

In [203]:
ruta = 'medallas.csv'

# cargar solo columnsa numericas y dejar faltantes como NaN(float)
array_medallas = np.genfromtxt(
    ruta,
    delimiter=',', # separador de columnas
    filling_values=np.nan, # las celdas vacías se rellenan con 0
    skip_header=1, # omitir primera fila de títulos o encabezados
    dtype=float, #convertir los datos a flotantes
    usecols=(0,1,2,3), # uso solo columnas numericas
    missing_values=''
)

# calcular la media por columna ignorando los NaN
medias_columnas = np.nanmean(array_medallas, axis=0)

# reemplaza cada NaN por la media de su columna
filas_nan, cols_nan = np.where(np.isnan(array_medallas))
array_medallas[filas_nan, cols_nan] = medias_columnas[cols_nan]

print('Medias por columna\n[Oro, Plata, Bronc, Total]\n', medias_columnas.round(2))

print('Primeras 5 filas imputadas por la media:')
print(array_medallas[:5])


Medias por columna
[Oro, Plata, Bronc, Total]
 [ 4.45  4.77  4.93 10.55]
Primeras 5 filas imputadas por la media:
[[ 4.453125  1.        2.        3.      ]
 [ 4.453125  2.        2.        4.      ]
 [17.        7.       22.       46.      ]
 [ 1.        1.        5.        7.      ]
 [ 4.453125  3.        4.        7.      ]]


#### Paso 3 — Explorar los datos importados con ufuncs

Una vez importados los datos como array, podemos aprovechar las ufuncs para obtener estadísticas rápidas:

In [229]:
# Columnas: 0=Oro, 1=Plata, 2=Bronce, 3=Total

print("Total de medallas de ORO en el medallero:  ", np.trunc(np.sum(array_medallas[:,0])))
print("Total de medallas de PLATA en el medallero:", np.trunc(np.sum(array_medallas[:,1])))
print("Total de medallas de BRONCE en el medallero:", np.trunc(np.sum(array_medallas[:,2])))
print()
print("Promedio de medallas de oro por país:", np.round(np.mean(array_medallas[:,0]), 2))
print("País con más medallas totales (índice):", np.argmax(array_medallas[:,3]))
print("Máximo de medallas totales:            ", np.max(array_medallas[:,3]))

Total de medallas de ORO en el medallero:   414.0
Total de medallas de PLATA en el medallero: 443.0
Total de medallas de BRONCE en el medallero: 458.0

Promedio de medallas de oro por país: 4.45
País con más medallas totales (índice): 25
Máximo de medallas totales:             113.0


Se puede mandar a un archivo txt los resultados obtenidos en la celda anterior

In [ ]:
with open('resultados.txt', 'w') as f:

### 3.2 Exportar datos con `save()`

Guarda los datos en binario, lo que ocupa menos espacio y se carga más rápido que un archivo de texto plano.Esto esIdeal para matrices grandes (millones de elementos).

Para guardar un array en un archivo binario de NumPy usamos `save()`. Necesita dos argumentos principales:

- La **ruta de destino** (normalmente con extensión `.npy`)
- El **array** a exportar

Luego se recupera con `load()`, conservando forma y tipo de dato exactamente.

In [213]:
array_ejemplo = np.array([[1, 2, 3],
                          [4, 5, 6]])

ruta_npy = 'mi_array_demo.npy'

# guardar en formato binario
np.save(ruta_npy, array_ejemplo)

# cargar el archivo creado
array_cargado = np.load(ruta_npy)
print('Array cargado correctamente')
print(array_cargado)

Array cargado correctamente
[[1 2 3]
 [4 5 6]]
