# Prueba I: NumPy y Análisis de Texto | CORRECCIÓN

Nombre: ALAN JAVIER REYES CASIERRA

Fecha: 30/4/2026

---

**Instrucciones generales**

1. El código debe ser claro, ordenado y reproducible.
2. El uso de IA , queda prohibido, el estudiante que incumpla esta norma, se le asigna la nota de cero y adicional el reporte con subdirección académica.
3. El estudiante debe verificar el archivo que sube al aula virtual, no se aceptan reclamos posteriores por haber subido un archivo incorrecto.


---

# Parte Teórica — 20%


**Pregunta 1.** ¿Qué es un dato y por qué por sí solo carece de significado?(4 puntos)


el dato es información sin procesar, podemos tener "42" y solo ser un número, carece de significado porque no se le ha asignado información, es como una pieza suelta de un rompecabezas

**Pregunta 2.** Explique los cuatro niveles de la pirámide DIKW y cada uno de ellos.(4 puntos)


1. Dato: dato crudo - pieza suelta, "42"
2. Información: datos procesados, 42 = edad de un piloto de carreras, aquí ya sabemos a qué rompecabezas pertenece la pieza
3. Conocimiento: saber cómo usar la información, sabemos en qué parte del rompecabezas puede ir la pieza
4. Sabiduría: aplicar el conocimiento, estamos seguros de lo que recolectamos antes y logramos ubicar la pieza correctamente

**Pregunta 3.** ¿Cuáles son las características principales de los datos estructurados, semi-estructurados y no estructurados? (4 puntos)


- Estructurados: están en filas y columnas, como en un excel
- Semi-estructurados: usan etiquetas que ayudan a identificar la información
- No estructurados: no tienen un formato definido, comparado a los otros dos tipos

**Pregunta 4.** ¿Qué es el análisis de datos y cuáles son sus etapas fundamentales? (4 puntos)


Es el proceso de **inspeccionar, limpiar, transformar e interpretar** los datos para descubrir información

**Pregunta 5.** De manera clara y justificada indicada, indique cuales son las ventajas de numpy sobre las estructuras convencionales de Python(al menos dos).(4 puntos)


1. numpy puede ahorrar mucho trabajo y tiempo con los métodos que ofrece, hace operaciones de una sola vez, no uno por uno
2. los métodos convencionales de python no tienen la eficiencia de python al hacer operaciones o buscar datos

---

# Parte Práctica (pondera 80%)

# Parte A

**Rúbrica**

1. Creación correcta de arreglos A, B y C y reporte de estructura (shape, ndim, size, tipo de dato): 3.2 pts
2. Indexación y slicing correctos: 2.4 pts
3. Operaciones de broadcasting y producto elemento a elemento: 2.4 pts


## A1. Creación y estructura

Genere los siguientes arreglos y para cada uno de ellos determina:

- Cantidad de elementos que tiene en cada dimensión
- Número de dimensiones del arreglo
- Total de elementos del arreglo
- Tipo de datos de los elementos del arreglo

1. Un arreglo llamado `A`, que empiece con valores desde el 5, avance de 5 en 5 y se detenga antes del 55.


In [298]:
import numpy as np
import re
from urllib import request
import time
from collections import Counter

A = np.arange(5, 55, 5)
print(A)
print(f'shape: {A.shape}')
print(f'ndim: {A.ndim}')
print(f'size: {A.size}')
print(f'dtype: {A.dtype}')

[ 5 10 15 20 25 30 35 40 45 50]
shape: (10,)
ndim: 1
size: 10
dtype: int64


2. Crea un arreglo llamado `B`, que contenga 6 valores, estos valores deben estar igualmente espaciados entre 0 y 1, incluyendo ambos extremos.


In [299]:
B = np.linspace(0, 1, 6)
print(B)
print(f'shape: {B.shape}')
print(f'ndim: {B.ndim}')
print(f'size: {B.size}')
print(f'dtype: {B.dtype}')

[0.  0.2 0.4 0.6 0.8 1. ]
shape: (6,)
ndim: 1
size: 6
dtype: float64


3. Crea el arreglo `C` según la imagen del enunciado.

![imagen1](imagen1.png)


In [300]:
C = np.arange(0, 25).reshape(5,5)
print(C)
print(f'shape: {C.shape}')
print(f'ndim: {C.ndim}')
print(f'size: {C.size}')
print(f'dtype: {C.dtype}')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
shape: (5, 5)
ndim: 2
size: 25
dtype: int64


## A2. Indexación y slicing

Usando el arreglo `C`:

1. Extraiga la segunda fila completa.


In [301]:
print(f'Segunda fila completa:\n{C[1,:]}')

Segunda fila completa:
[5 6 7 8 9]


2. Extraiga la tercera columna completa.


In [302]:
print(f'Tercera columna completa:\n{C[:,2]}')

Tercera columna completa:
[ 2  7 12 17 22]


3. Extraiga la submatriz (fila 1, 2, 3 y columnas 1, 2, 3).


In [303]:
print(f'Submatriz (fila 1, 2, 3 y columnas 1, 2, 3)\n{C[1:4,1:4]}')

Submatriz (fila 1, 2, 3 y columnas 1, 2, 3)
[[ 6  7  8]
 [11 12 13]
 [16 17 18]]


## A3. Broadcasting y operaciones

Dados los siguientes arreglos:

```python
A1 = np.array([[11, 22], [33, 44]])
B1 = np.array([[55, 66], [77, 88]])
```

1. Reste 10 a todos los elementos de la matriz `A1`.


In [304]:
A1 = np.array([[11, 22], [33, 44]])
B1 = np.array([[55, 66], [77, 88]])

A1 = A1 + (-10)
print(A1)

[[ 1 12]
 [23 34]]


2. Realice el producto elemento por elemento (Hadamard) entre `A1` y `B1`.


In [305]:
print(np.multiply(A1, B1))

[[  55  792]
 [1771 2992]]


---

# Parte B

**Rúbrica**

1. Carga correcta del CSV y selección de columnas numéricas: 4.8 pts
2. Diagnóstico de NaN y cálculos globales ignorando NaN: 4.8 pts
3. Promedios por eje y redondeo solicitado: 4.8 pts
4. Imputación correcta por columna y obtención de índices solicitados: 4.8 pts
5. Guardado correcto en formato .npy: 4.8 pts

El INAMI tiene un registro de temperaturas en grados Celsius del año 2026 para los meses de enero, febrero, marzo y abril de las capitales de provincia del Ecuador.

Use el archivo `temperaturas-ecuador.csv` como fuente de datos.

Este archivo tiene las columnas: Ciudad, Enero, Febrero, Marzo, Abril.

Primero cargue solo las columnas numéricas en una matriz llamada `temperaturas_ecuador` usando numpy.


In [306]:
temperaturas_ecuador = np.genfromtxt('temperaturas-ecuador.csv',
                                      delimiter=',',
                                      skip_header=1,
                                      usecols=(1, 2, 3, 4)
                                      )

## B1. Diagnóstico inicial

1. Indique cuántos NaN hay en total en el arreglo.


In [307]:
print(f'NaN totales: {np.isnan(temperaturas_ecuador).sum()}')

NaN totales: 3


2. Calcule suma y promedio global ignorando los NaN.


In [308]:
print(f'Suma global: {np.nansum(temperaturas_ecuador).round(2)}')
print(f'Promedio global: {np.nanmean(temperaturas_ecuador).round(2)}')

Suma global: 1945.65
Promedio global: 20.92


## B2. Estadística por eje

1. Redondee a dos decimales los valores de la matriz.


In [309]:
temperaturas_ecuador =np.round(temperaturas_ecuador, 2)

2. Calcule promedio de cada columna ignorando NaN.


In [310]:
print(f'Promedio por columna ignorando NaN:\n{np.nanmean(temperaturas_ecuador, axis=0).round(2)}')

Promedio por columna ignorando NaN:
[21.01 21.27 21.11 20.28]


3. Calcule promedio de cada fila ignorando NaN.


In [311]:
print(f'Promedio por fila ignorando NaN:\n{np.nanmean(temperaturas_ecuador, axis=1).round(2)}')

Promedio por fila ignorando NaN:
[16.62 14.2  15.82 11.42 13.2  12.77 27.4  26.51 28.   27.91 15.34 18.5
 26.71 25.56 23.5  24.06 25.36 22.92 14.82 25.93 23.97 24.62 15.21 22.35]


## B3. Imputación simple

1. Crea una nueva matriz, llamada `matriz_limpia` y reemplace los NaN de cada columna por el **promedio de su propia columna**, utilice el promedio redondeado a dos decimales.


In [312]:
matriz_limpia = np.where(np.isnan(temperaturas_ecuador), np.nanmean(temperaturas_ecuador, axis=0).round(2), temperaturas_ecuador)

2. Identifique el índice de la columna con mayor promedio.


In [313]:
prom_col = np.mean(matriz_limpia, axis=0).round(2)
print(f'Indice de la columna con mayor promedio: {np.argmax(prom_col)}')

Indice de la columna con mayor promedio: 1


3. Identifique el índice de la fila con el mayor promedio.


In [314]:
prom_fil = np.mean(matriz_limpia, axis=1).round(2)
print(f'Indice de la fila con mayor promedio: {np.argmax(prom_fil)}')

Indice de la fila con mayor promedio: 8


## B4. Guardar la matriz_limpia en un archivo .npy


In [315]:
np.save('resultado_temperaturas.npy', matriz_limpia)
comprobar = np.load('resultado_temperaturas.npy')
print(f'Se creó con contenido? {np.array_equal(comprobar, matriz_limpia)}')

Se creó con contenido? True


---

# Parte C - Análisis de texto

**Rúbrica**

1. Limpieza correcta del texto (minúsculas, limpieza de caracteres, tokenización): 7.2 pts
2. Frecuencias, conteo de únicas y filtro por longitud: 7.2 pts
3. Medición de tiempo del proceso: 2.4 pts
4. Generación correcta de reporte_texto.txt con todos los campos: 7.2 pts

Usa la siguiente url que contiene la canción WONDERWALL de OASIS:
https://raw.githubusercontent.com/juankgonzalez22/Prueba-I-Analisis/refs/heads/main/Wonderwall.txt


## C1. Limpieza básica

1. Mida el tiempo desde que empieza a realizar esta actividad.
2. Cargue el texto a una variable y pase todo a minúsculas, tome en cuenta que la canción solo es este fragmento de todo el txt(los metadatos de cabecera y pie de pagina deben omitirse en la carga de texto) .  
![imagen1](wonderwall.png)
3. Elimine signos de puntuación o caracteres especiales.
4. Tokenice el texto.


In [316]:
url = 'https://raw.githubusercontent.com/juankgonzalez22/Prueba-I-Analisis/refs/heads/main/Wonderwall.txt'

# 1
inicioAB = time.time()
respuesta = request.urlopen(url)
texto = respuesta.read().decode('utf-8')
finA = time.time()
tiempo_ms = round((finA - inicioAB) * 1000, 3)

# 2
inicio_texto = texto.find('=== START OF THE SONG WONDERWALL BY OASIS ===') + 1
fin_texto = texto.find('=== END OF THE SONG WONDERWALL BY OASIS ===')
cancion = texto[inicio_texto:fin_texto]
cancion_minusculas = cancion.lower()

# 3
cancion_solo_letras = re.sub(r'[^a-z\s]', ' ', cancion_minusculas)

# 4
palabras = cancion_solo_letras.split()

## C2. Frecuencias

3. Filtre del texto solo palabras de longitud mayor a 4.
1. Obtenga las 5 palabras más frecuentes del texto previamente filtrado.
1. Muestre la cantidad de palabras únicas existente en toda la canción(sin haber aplicado el filtro de longitud mayor a 4).
1. Mida el tiempo de ejecución total hasta que terminó todo el proceso desde el inicio de C1, hasta que terminó la actividad 3 de C2.


In [317]:
# 1
palabras_filtradas = [p for p in palabras if len(p) > 4]

# 2
contador = Counter(palabras_filtradas)
top_5 = contador.most_common(5)

print('PALABRA  FRECUENCIA')
for palabra, frecuencia in top_5:
    print(f'{palabra}:\t {frecuencia}')

# 3
unicas = len(Counter(palabras))
print(f'Cantidad de palabras únicas: {unicas}')

# 4
finB = time.time()
tiempo_s = round(finB - inicioAB, 3)

PALABRA  FRECUENCIA
gonna:	 9
saves:	 9
maybe:	 6
wonderwall:	 4
there:	 4
Cantidad de palabras únicas: 88


## C3. Reporte de texto

Genere un archivo de salida txt llamado `reporte_texto.txt`, este archivo debe decir:

- Total de palabras en todo el texto: ....
- Total de palabras únicas en todo el texto: ....
- Top 5 palabras más frecuentes de la canción(habiendo aplicado el filtro de palabras de longitud mayor a 4): .....
- Tiempo total en segundos (C1 A C2)


In [318]:
with open('reporte_texto.txt', 'w', encoding='utf-8') as f:
    f.write(f'Total de palabras en todo el texto: {len(palabras)}\n')
    f.write(f'Total de palabras ÚNICAS en todo el texto: {unicas}\n')
    f.write('TOP 5 palabras más frecuentes\n')
    for palabra, frecuencia in top_5:
        f.write(f'{palabra}:\t {frecuencia}\n')
    
    f.write(f'Tiempo total en segundos (C1 A C2): {tiempo_s}s')
    

---

# Parte D - Integrador

**Rúbrica**

1. Construcción correcta de matriz aleatoria y aplicación de condiciones de bordes: 4.8 pts
2. Cálculos por ejes y máximo con posición: 6.4 pts
3. Extracción de valores >= 300 y porcentaje: 6.4 pts
4. Clasificación en tres niveles: 6.4 pts


## D1.

Cree una matriz cuadrada `mi_matriz` de tamaño 80x80 con valores enteros aleatorios entre 10 y 500.


In [319]:
dim = [80, 80]
mi_matriz = np.random.randint(10, 501, size=dim).astype(np.int64)

## D2.

Modifique la matriz para cumplir estas condiciones:

- La fila superior (primera fila) debe ser todo unos.
- La fila inferior (última fila) debe ser todo ceros.


In [320]:
mi_matriz[0,:] = 1
mi_matriz[-1,:] = 0
print(mi_matriz)

[[  1   1   1 ...   1   1   1]
 [229 325 375 ...  57 209 448]
 [362 307 195 ... 474 436 275]
 ...
 [450 309 301 ... 384 334 455]
 [ 89 128 287 ... 382 280 219]
 [  0   0   0 ...   0   0   0]]


## D3.

Calcule sobre la matriz final:

- Suma por filas
- Promedio por columnas
- Valor máximo y su posición


In [321]:
sum_filas = np.sum(mi_matriz, axis=1)
print(f'Suma por filas:\n{sum_filas}')

mean_columnas = np.mean(mi_matriz, axis=0).round(2)
print(f'\nPromedio por columnas:\n{mean_columnas}')

print(f'\nValor máximo mi_matriz: {np.max(mi_matriz)}, posición: {np.argmax(mi_matriz)}')
print(f'Valor máximo sum_filas: {np.max(sum_filas)}, posición: {np.argmax(sum_filas)}')
print(f'Valor máximo mean_columnas: {np.max(mean_columnas)}, posición: {np.argmax(mean_columnas)}')

Suma por filas:
[   80 18666 22624 20266 20438 20404 19309 20135 19434 20656 18973 20325
 19588 19383 20821 21607 21703 20165 21814 19258 19942 21545 18967 19498
 20443 20023 21031 21395 22154 22028 19725 19911 19737 19271 21989 20751
 21035 18802 19512 20696 21692 19460 18571 19881 18604 20475 20244 21512
 21319 20660 21524 19874 20684 22380 20888 20739 18947 18310 19257 21317
 19119 20358 20988 18981 19672 20492 19658 20609 19265 19147 21871 19159
 20180 19093 20041 20571 19377 20100 20024     0]

Promedio por columnas:
[241.34 248.12 252.16 253.46 256.82 234.98 243.45 251.21 263.55 253.18
 259.08 218.55 244.26 271.85 250.99 257.66 245.59 243.6  246.16 271.51
 237.04 261.36 222.61 275.35 239.24 252.7  247.36 253.25 230.35 242.24
 260.1  245.18 218.39 236.01 280.24 247.02 250.4  257.7  234.91 276.61
 241.35 232.6  249.95 238.94 251.15 252.38 245.15 232.5  276.62 261.49
 231.06 246.39 236.46 237.04 265.48 221.22 244.2  237.38 250.18 226.42
 240.81 262.32 253.56 246.61 226.24 219.6  239

## D4.

Extraiga todos los elementos mayores o iguales a 300 y reporte:

- Cantidad
- Porcentaje respecto al total


In [322]:
cantidad = np.count_nonzero(mi_matriz >= 300)
print(f'Cantidad elementos >= 300: {cantidad}')

porcentaje = ((cantidad/mi_matriz.size) * 100).round(2)
print(f'% respecto al total (6400): {porcentaje}%')

Cantidad elementos >= 300: 2538
% respecto al total (6400): 39.66%


## D5.

Genere una matriz de clasificación ` usando la matriz final:

- "bajo" si valor <= 30
- "medio" si valor entre 200 y 300
- "alto" si valor >= 400


In [323]:
clasificacion = mi_matriz.copy()

clasificacion = np.where(clasificacion <= 30, 'bajo', 
                         np.where((clasificacion >= 200) & (clasificacion <= 300), 'medio',
                                  np.where(clasificacion >= 400, 'alto', clasificacion)))

print(clasificacion)

bajos = np.sum(clasificacion == 'bajo')
medios = np.sum(clasificacion == 'medio')
altos = np.sum(clasificacion == 'alto')
bma = bajos + medios + altos

print('\nTOTALES')
print(f'> bajo: {bajos}')
print(f'> medio: {medios}')
print(f'> alto: {altos}')
print(f'> Sin clasificar: {mi_matriz.size - bma}')


[['bajo' 'bajo' 'bajo' ... 'bajo' 'bajo' 'bajo']
 ['medio' '325' '375' ... '57' 'medio' 'alto']
 ['362' '307' '195' ... 'alto' 'alto' 'medio']
 ...
 ['alto' '309' '301' ... '384' '334' 'alto']
 ['89' '128' 'medio' ... '382' 'medio' 'medio']
 ['bajo' 'bajo' 'bajo' ... 'bajo' 'bajo' 'bajo']]

TOTALES
> bajo: 443
> medio: 1295
> alto: 1249
> Sin clasificar: 3413


# ENTREGABLE
COMPRIMIR TODO EL CONTENIDO DE LA CARPETA QUE DESCARGO PARA LA PRUEBA I , RENOMBRARLA A "APELLIDO_NOMBRE_PRUEBA1.zip" Y SUBIR AL AULA VIRTUAL