# Arrays
## Arrays
### Arrays

*NumPy* nos brinda un **nuevo tipo de datos** que es una estructura de datos, en realidad, y que se llama **array**.  

Como a mí me gusta explicar las cosas visualmente, primero vamos a crear nuestro primer array :D

In [1]:
print("hola mundo")

hola mundo


In [2]:
import numpy as np
import time

In [3]:
mi_array = np.array([1, 2, 3, 4, 5])
display(mi_array)

array([1, 2, 3, 4, 5])

Puede que en este momento esten pensando "eso es una lista*". Bueno, la verdad que es muy parecido, pero el array de NumPy es **mucho más rápido** y **más poderoso**, y a esto lo vamos a comprobar en un instante. Pero antes, para despejar toda duda…

In [4]:
type(mi_array)

numpy.ndarray

Para comparar la *velocidad* de un **array** versus una **lista**, tenemos que trabajar con objetos más grandes y pesados, donde la velocidad va a ser más evidente.

Para eso voy a crear dos objetos nuevos (una lista y un array) que contengan **un millón de elementos**:

In [5]:
lista_grande = list(range(1000000))
array_grande = np.array(lista_grande)

In [6]:
type(lista_grande)

list

In [7]:
type(array_grande)

numpy.ndarray

Para medir el tiempo, he tenido que importar en la primera celda de este cuaderno, una librería de python llamada `time`, que nos brinda algunas herramientas para medir el tiempo que toma en ejecutarse un determinado código.

Imaginemos que quiero obtener el **cuadrado** de cada número que hay en mis nuevos objetos. Estamos hablando de multiplicar al cuadrado un millón de números en cada uno de ellos. El objetivo de hacer esto, es para medir cuánto tiempo tarda la *lista*, y cuánto tarda el *array*, para ver **cuál es más eficiente**.

Para lograr eso, `time` me va a permitir crear marcas de tiempo antes y después de ejecutar mi código, y así poder ver cuánto ha durado su ejecución:

In [8]:
inicio_lista = time.time()
for i in lista_grande:
    i ** 2
fin_lista = time.time()
print(f"Tiempo lista demorado: {fin_lista - inicio_lista}")

Tiempo lista demorado: 0.18639826774597168


Ahora voy a hacer lo mismo pero en vez de trabajar con `lista_grande`, voy a trabajar con `array_grande`:

In [9]:
inicio_array = time.time()
array_grande ** 2
fin_array = time.time()
print(f"Tiempo array demorado: {fin_array - inicio_array}")

Tiempo array demorado: 0.006689548492431641


Observa la eficiencia con la que ha trabajado NumPy a través del array, para comenzar a comprender el poder de trabajar con este recurso.

NumPy es una herramienta esencial en el mundo del Data Science por su **eficiencia**, por su **facilidad de uso** y por su **amplia adopción** en la comunidad científica y analítica.

En las siguientes lecciones nos va a quedar bien clara su capacidad para realizar operaciones complejas y para manejar grandes conjuntos de datos, lo cual lo hace insustituible en el análisis de datos.

# Tipos de Arrays

Vamos a profundizar en la principal **estructura de datos** en NumPy, que son los **arrays**.

Vamos a conocer los **dos tipos de array** que podemos crear, y cómo manipular estas estructuras.

Ya hemos conocido a los arrays de NumPy, y hemos visto que básicamente un array es:
* una **cuadrícula de valores**,
* que tienen que ser todos **del mismo tipo** (pueden ser integers, floats, strings, o lo que sea, pero todos del mismo tipo),
* y está **indexado**, o sea que tiene un índice, como la mayoría de las estructuras de datos que vimos hasta ahora.

Vamos a crear un array bien sencillo:

In [11]:
array = np.array([1, 2, 3])

Este es un **array unidimensional**, porque tiene **una sola dimensión**. Tiene un **largo**.

De hecho si quiero comprobar su largo…

In [12]:
len(array)

3

Hagamos una comprobación más, e intentemos conocer la **forma** de este array ¿Para ello usaremos la propiedad `shape` que usábamos para conocer la forma de un DataFrame?

In [15]:
array.shape
# array.ndim

(3,)

Como puede ver, he pedido conocer el **largo** y el **alto** de mi array, pero solo me dice el largo, y no hay ninguna medida para el alto, porque no lo tiene. Solo tiene **una dimensión**, que es el largo.

Ahora creemos un **array de dos dimensiones**:

In [20]:
array_2d = np.array([[1, 2, 3],
                    [4, 5, 6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

Esto ya se ve distinto. Las dos *listas* que le he pasado, se han ordenado una arriba de la otra, y tenemos una especie de *tabla*, pero no es una tabla, es un **array de dos dimensiones**.

Voy a consultar el largo (`len`) de este array. ¿Voy a obtener **6**, debido a que tiene 6 elementos? ¿O tal vez debería obtener **3** ya que ese es el ancho de esta especie de *tabla*?

In [21]:
len(array_2d)

2

Esto sí que es curioso ¿verdad?. Ni 6, ni 3.

Este array tiene un **largo de 2**, a pesar de que sus elementos tienen 3 números cada uno. ¿Entonces por qué dice que tiene un largo de 2?

Porque en realidad este array tiene **2 elementos**, que son cada uno de los conjuntos de 3 números:
* Elemento #1: **[1, 2, 3]**
* Elemento #2: **[4, 5, 6]**


¿Y si consultamos su **forma**?

In [22]:
array_2d.shape

(2, 3)

Bueno, ahora podemos ver sus **dos dimensiones**. Nuestro array tiene:
* **2 unidades de alto**
* **3 unidades de largo**.



# Manipulacion de Arrays

Algo que también podemos hacer es **concatenar** a nuestros arrays.

In [23]:
x = [1, 2, 3]
y = [1, 2, 3]
z = [1, 2, 3]

In [25]:
np.concatenate([x, y, z])

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

Como puedes ver, el argumento que hemos pasado a `concatenate()` es una lista de listas a concatenar, y esto a devuelto un **array** (porque lo hicimos con NumPy) **de una dimensión**.

Pero el método `concatenate()` de NumPy tiene un segundo argumento, que es el **"Eje"**, o **"Axis"**, que nos permite especificar a lo largo de qué eje será concatenado el resultado.

- axis=0 → corresponde a las filas (vertical, lo que podrías asociar al eje Y)
- axis=1 → corresponde a las columnas (horizontal, lo que podrías asociar al eje X).


Voy a crear **2 arrays de dos dimensiones**, y lo voy a concatenar sobre el eje 1 `(axis=1)`:

In [29]:
a = [[1, 2],
     [3, 4]]
b = [[5, 6],
     [7, 8]]

np.concatenate([a, b], axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

Y si concateno esos mismos arrays pero sobre el eje `0`:

In [30]:
np.concatenate([a,b], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Hay algunas estrategias extra para manipular arrays, como por ejemplo **cambiar su forma**.

Para hacer eso, primero voy a tomar el último array que hemos creado y lo voy a alamacenar en la variable `array_concatenado`:

In [31]:
array_concatenado = np.concatenate([a,b], axis=0)
array_concatenado

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Si quiero conocer la **forma** de este array…

In [32]:
array_concatenado.shape

(4, 2)

… veo que es de **4 por 2**, porque tiene **cuatro filas** y **dos columnas**.

Pero voy a **cambiar su forma**, pidiéndole que se reorganice para ser un array de **2 filas** por **4 columnas**, usando el método `reshape()`:

In [35]:
array_reformado = array_concatenado.reshape(2, 4)
array_reformado

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

También puedo hacer cosas como **sumar arrays**:

In [38]:
array_sumado = array_reformado + array_reformado
array_sumado

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

O multiplicarlos:

In [41]:
array_multiplicado = array_reformado * array_reformado
array_multiplicado

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

Básicamente puedes usar todos los operadores matemáticos que conocemos para hacer cálculos con arrays (ya sean uni o bidimensionales).

Un detalle específico en NumPy que me gustaría mostrar es cómo hacemos en este caso el cálculo de la **raíz cuadrada**, ya que es con un método especial de NumPy que se llama `sqrt()`, que significa **square root** (o *raíz cuadrada*), y que se aplica así:

In [42]:
raices = np.sqrt(array_multiplicado)
raices

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

# Slicing de Arrays

El **slicing** (o *rebanado*) nos permite extraer **subconjuntos** de un array usando la sintaxis:

```
array[inicio:fin:paso]
```

* **inicio**: índice donde empieza el slice (incluido). Si se omite, arranca desde el principio.
* **fin**: índice donde termina el slice (excluido). Si se omite, llega hasta el final.
* **paso**: de cuánto en cuánto salta. Si se omite, el paso es 1.

Vamos a crear un array de ejemplo para practicar:

In [45]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

## Slicing básico en arrays 1D

Podemos extraer elementos con `array[inicio:fin]`. El índice `fin` **no se incluye** en el resultado:

In [55]:
#primeros 4 elementos
print(f"Primeros 4 elementos: {arr[:4]}")
#del indice 2 al 6
print(f"Del indice 2 al 6: {arr[2:7]}")
#ultimos 3 elementos
print(f"Últimos 3 elementos: {arr[-3:]}")


Primeros 4 elementos: [10 20 30 40]
Del indice 2 al 6: [30 40 50 60 70]
Últimos 3 elementos: [70 80 90]


## Slicing con paso

Agregando un tercer valor podemos indicar el **paso** (`step`), es decir, de cuánto en cuánto avanzamos:

In [60]:
#cada dos elementos
print(f"Cada dos elementos: {arr[::2]}")
#Paso 3 desde indice 1
print(f"Paso 3 desde índice 1: {arr[1::3]}")
#array invertido con paso de -1
print(f"Array invertido con paso de -1: {arr[::-1]}")

Cada dos elementos: [10 30 50 70 90]
Paso 3 desde índice 1: [20 50 80]
Array invertido con paso de -1: [90 80 70 60 50 40 30 20 10]


## Slicing en arrays 2D

En arrays de dos dimensiones la sintaxis es `array[filas, columnas]`. Podemos aplicar slicing en **ambas dimensiones** al mismo tiempo:

In [65]:
matriz = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
print(f"Matiz completa:\n{matriz}")

Matiz completa:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [75]:
#Primera fila completa
print(f"Primera fila: {matriz[0,:]}")
#Primera comlumna completa
print(f"Primera columna: {matriz[:,0]}")
#Submatriz: primeras dos filas y columnas 1 a 3
print(f"Submatriz: primeras dos filas y columnas 1 a 3:\n{matriz[:2,0:3]}")

Primera fila: [1 2 3 4]
Primera columna: [1 5 9]
Submatriz: primeras dos filas y columnas 1 a 3:
[[1 2 3]
 [5 6 7]]


## Importante: el slicing devuelve una vista, no una copia

A diferencia de las listas de Python, el slicing en NumPy devuelve una **vista** del array original. Eso significa que si modificas el slice, **también se modifica el array original**. Si necesitas una copia independiente, usa `.copy()`: