# Deber Semana 2 — NumPy Aplicado
## Análisis de Datos — TDSD353

| | |
|---|---|
| **Paralelo** | GR2 |
| **Docente** | Juan Carlos Gonzalez Ortiz |
| **Estudiante** | Alan Javier Reyes Casierra |
| **Fecha de entrega** | lunes, 20 de abril de 2026 |

---

**Indicaciones generales:**
- Resuelve cada ejercicio en la celda de código que se indica. No borres las instrucciones.
- Antes de entregar, haz `Kernel → Restart & Run All` para verificar que todo corra sin problemas.
- Se califica: código correcto, que se ejecute, y las respuestas escritas donde se pida.
- Entrega este `.ipynb` con todas las celdas ejecutadas.

---
## Parte 1 — Creación y estructura de arrays

En esta sección vas a practicar las distintas formas de crear arrays en NumPy y cómo inspeccionar sus propiedades.

In [1]:
# Ejecuta esta celda primero
import numpy as np
import time
print('NumPy listo, versión:', np.__version__)

NumPy listo, versión: 2.4.2


### Ejercicio 1 — Creación de arrays (2 pts)

Crea los siguientes arrays y muéstralos con `print`:

a) Un array 1D con las notas de 8 estudiantes (invéntate valores entre 5.0 y 10.0).  
b) Una matriz de 4×5 llena de ceros.  
c) Un array con 10 valores equiespaciados entre 0 y 100 usando `linspace`.  
d) Una matriz identidad de 5×5.  
e) Un array de 12 enteros aleatorios entre 1 y 50.

In [54]:
# --- Ejercicio 1: escribe tu código aquí ---
# a)
notas = np.random.rand(8) * 5 + 5
notas = notas.round(2)
print(f'Notas de 8 estudiantes:\n{notas}')

# b)
m_zeros = np.zeros([4, 5])
print('matriz 4x5 de ceros:\n', m_zeros)

# c)
arr_equid = np.linspace(0, 100, 10)
arr_equid = arr_equid.round(2)
print(f'array con 10 valores equiespaciados entre 0 y 100:\n{arr_equid}')

# d)
m_ident = np.eye(5)
print(f'matriz identidad 5x5:\n{m_ident}')

# e)
arr_ent_al = np.random.randint(1, 51, 12)
print(f'array de 12 enteros aleatorios entre 1 y 50\n{arr_ent_al}')

Notas de 8 estudiantes:
[9.99 6.37 7.76 5.21 5.8  5.73 8.07 9.36]
matriz 4x5 de ceros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
array con 10 valores equiespaciados entre 0 y 100:
[  0.    11.11  22.22  33.33  44.44  55.56  66.67  77.78  88.89 100.  ]
matriz identidad 5x5:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
array de 12 enteros aleatorios entre 1 y 50
[41 37 10 20 31 50 30  5 45 42 11 18]


### Ejercicio 2 — Propiedades y reshape (2 pts)

Usando el array de 12 enteros aleatorios del ejercicio anterior (literal e):

a) Imprime su `shape`, `ndim`, `size` y `dtype`.  
b) Reacomódalo en una matriz de 3×4 con `reshape` y muéstrala.  
c) Transpón esa matriz con `.T` e imprime el resultado.  
d) Aplana la matriz transpuesta con `flatten()` y muestra el array resultante.  
e) Convierte el array original a tipo `float64` con `astype()` e imprime su `dtype` para verificar.

In [55]:
# --- Ejercicio 2: escribe tu código aquí ---
# a)
print(f'Para el array -> {arr_ent_al}')
print(f'shape: {arr_ent_al.shape}')
print(f'ndim: {arr_ent_al.ndim}')
print(f'size: {arr_ent_al.size}')
print(f'dtype: {arr_ent_al.dtype}')

# b)
arr_ent_al_ac = np.reshape(arr_ent_al, [3, 4])
print(f'\nReacomodado 3x4:\n{arr_ent_al_ac}')
# funciona porque el producto de las dimensiones (3*4) nos da el mismo valor que el tamaño

# c)
arr_ent_al_ac_t = arr_ent_al_ac.T
print(f'\nTranspuesta:\n{arr_ent_al_ac_t}')

# d)
print(f'\nAplanada:\n{arr_ent_al_ac_t.flatten()}')

# e)
arr_ent_al = arr_ent_al.astype(np.float64)
print(f'\nOriginal (dtype: int32) a float64: {arr_ent_al.dtype}')

Para el array -> [41 37 10 20 31 50 30  5 45 42 11 18]
shape: (12,)
ndim: 1
size: 12
dtype: int32

Reacomodado 3x4:
[[41 37 10 20]
 [31 50 30  5]
 [45 42 11 18]]

Transpuesta:
[[41 31 45]
 [37 50 42]
 [10 30 11]
 [20  5 18]]

Aplanada:
[41 31 45 37 50 42 10 30 11 20  5 18]

Original (dtype: int32) a float64: float64


---
## Parte 2 — Indexación y segmentación

Aquí vamos a trabajar con slicing, indexación booleana y fancy indexing. Son herramientas fundamentales para filtrar y seleccionar datos.

### Ejercicio 3 — Slicing en 1D y 2D (2 pts)

Dado el siguiente array y matriz:

In [56]:
# No modifiques esta celda, solo ejecútala
temperaturas = np.array([22.5, 24.1, 19.8, 26.3, 21.0, 28.7, 23.4, 20.6, 27.9, 25.2])
ventas = np.arange(1, 21).reshape(4, 5)  # ventas semanales por sucursal (4 sucursales, 5 semanas)
print('Temperaturas:', temperaturas)
print('Ventas:\n', ventas)

Temperaturas: [22.5 24.1 19.8 26.3 21.  28.7 23.4 20.6 27.9 25.2]
Ventas:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


Ahora resuelve:

a) Del array `temperaturas`: obtén los elementos del índice 2 al 6 (sin incluir el 7).  
b) Del array `temperaturas`: obtén los elementos en posiciones pares (0, 2, 4, ...) usando paso en el slicing.  
c) Invierte el array `temperaturas` (muéstralo al revés).  
d) De la matriz `ventas`: extrae las filas 1 y 2 (sucursales 2 y 3), columnas 0 a 2.  
e) De la matriz `ventas`: extrae toda la columna 3 (semana 4).

In [63]:
# --- Ejercicio 3: escribe tu código aquí ---
# a)
print(f'elementos del indice 2 al 6: {temperaturas[2:7]}')

# b)
print(f'elementos en posiciones pares: {temperaturas[::2]}')

# c)
print(f'invetido: {temperaturas[::-1]}')

# d)
print(f'filas 1 y 2 de ventas:\n{ventas[1:3, 0:3]}')

# e)
print(f'toda la columna 3:\n{ventas[:,3]}')

elementos del indice 2 al 6: [19.8 26.3 21.  28.7 23.4]
elementos en posiciones pares: [22.5 19.8 21.  23.4 27.9]
invetido: [25.2 27.9 20.6 23.4 28.7 21.  26.3 19.8 24.1 22.5]
filas 1 y 2 de ventas:
[[ 6  7  8]
 [11 12 13]]
toda la columna 3:
[ 4  9 14 19]


### Ejercicio 4 — Indexación booleana, fancy indexing y np.where (2 pts)

Sigue trabajando con el array `temperaturas` definido arriba.

a) Usa una máscara booleana para obtener solo las temperaturas mayores a 24.  
b) Usa fancy indexing para obtener las temperaturas en las posiciones [1, 4, 7].  
c) Usa `np.where` para crear un nuevo array donde las temperaturas mayores a 25 se mantengan iguales, y las menores o iguales se reemplacen por 0.  
d) Usa `np.where` para encontrar los **índices** de las temperaturas menores a 22.

In [81]:
# --- Ejercicio 4: escribe tu código aquí ---

# a)
t_mayores_24 = temperaturas[temperaturas > 24]
print(f'temperaturas mayores a 24: {t_mayores_24}')

# b)
print(f'temperaturas en las posiciones [1, 4, 7]: {temperaturas[[1, 4, 7]]}')

# c)
nuevas_temp = np.where(temperaturas > 25, temperaturas, 0)
print(f'temperaturas menores a 25 reemplazadas por 0: {nuevas_temp}')

# d)
print(f'índices temperaturas menores a 22: {np.where(temperaturas < 22)[0]}')

temperaturas mayores a 24: [24.1 26.3 28.7 27.9 25.2]
temperaturas en las posiciones [1, 4, 7]: [24.1 21.  20.6]
temperaturas menores a 25 reemplazadas por 0: [ 0.   0.   0.  26.3  0.  28.7  0.   0.  27.9 25.2]
índices temperaturas menores a 22: [2 4 7]


---
## Parte 3 — Operaciones matemáticas y broadcasting

NumPy permite hacer operaciones vectorizadas: es decir, operar arrays enteros sin usar bucles `for`. Eso es lo que lo hace rápido.

### Ejercicio 5 — Operaciones elemento a elemento y escalares (1.5 pts)

Tenemos los precios de 6 productos en dos meses:

In [82]:
# No modifiques esta celda
precios_enero = np.array([12.50, 8.90, 15.00, 22.30, 5.60, 9.75])
precios_febrero = np.array([13.00, 8.50, 16.20, 21.80, 6.10, 10.00])
print('Enero:', precios_enero)
print('Febrero:', precios_febrero)

Enero: [12.5   8.9  15.   22.3   5.6   9.75]
Febrero: [13.   8.5 16.2 21.8  6.1 10. ]


a) Calcula la diferencia de precios entre febrero y enero (elemento a elemento).  
b) Calcula el precio promedio de cada producto entre los dos meses: $(enero + febrero) / 2$  
c) Aplica un aumento del 12% a todos los precios de febrero (multiplicar por 1.12). Esto es broadcasting con escalar.  
d) Usando `np.power`, calcula el cuadrado de los precios de enero.

In [101]:
# --- Ejercicio 5: escribe tu código aquí ---
# a)
print(f'diferencias de precios: {precios_febrero - precios_enero}')

# b)
print(f'promedio: {((precios_enero + precios_febrero)/2).round(2)}')

# c)
print(f'precios_febrero + 12%: {(precios_febrero * 1.12).round(2)}')

# d)
print(f'cuadrado de los precios de enero: {np.power(precios_enero, 2).round(2)}')

diferencias de precios: [ 0.5  -0.4   1.2  -0.5   0.5   0.25]
promedio: [12.75  8.7  15.6  22.05  5.85  9.88]
precios_febrero + 12%: [14.56  9.52 18.14 24.42  6.83 11.2 ]
cuadrado de los precios de enero: [156.25  79.21 225.   497.29  31.36  95.06]


### Ejercicio 6 — Broadcasting con matrices (1.5 pts)

Vamos a usar la matriz `ventas` (4 sucursales × 5 semanas) que ya definimos arriba.

In [100]:
# Recordatorio
print('Ventas (4 sucursales x 5 semanas):\n', ventas)

Ventas (4 sucursales x 5 semanas):
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


a) Supón que cada semana tiene un factor de ajuste distinto: `ajuste = np.array([1.0, 1.1, 0.95, 1.2, 1.05])`. Multiplica `ventas` por `ajuste` usando broadcasting y muestra el resultado. Fíjate cómo NumPy expande el vector para operar con la matriz.  
b) Calcula la raíz cuadrada de cada elemento de `ventas` con `np.sqrt`.  
c) Redondea los resultados del literal b) a 2 decimales con `np.round`.

In [106]:
# --- Ejercicio 6: escribe tu código aquí ---
# a)
ajuste = np.array([1.0, 1.1, 0.95, 1.2, 1.05])
print(f'ventas x ajuste:\n{ventas * ajuste}')

# b) y c)
print(f'raíces cuadradas de ventas:\n{np.sqrt(ventas).round(2)}')

ventas x ajuste:
[[ 1.    2.2   2.85  4.8   5.25]
 [ 6.    7.7   7.6  10.8  10.5 ]
 [11.   13.2  12.35 16.8  15.75]
 [16.   18.7  17.1  22.8  21.  ]]
raíces cuadradas de ventas:
[[1.   1.41 1.73 2.   2.24]
 [2.45 2.65 2.83 3.   3.16]
 [3.32 3.46 3.61 3.74 3.87]
 [4.   4.12 4.24 4.36 4.47]]


---
## Parte 4 — Estadísticas y agregaciones

Las funciones de agregación son lo que más vas a usar en análisis de datos: promedios, desviaciones, máximos, mínimos, etc.

### Ejercicio 7 — Estadísticas básicas y por eje (2 pts)

Vamos a simular calificaciones de 5 estudiantes en 4 materias:

In [107]:
# No modifiques esta celda
np.random.seed(10)  # para que todos tengamos los mismos datos
calificaciones = np.random.randint(40, 100, size=(5, 4)).astype(float)
materias = ['Matemáticas', 'Física', 'Programación', 'Estadística']
estudiantes = ['Est_1', 'Est_2', 'Est_3', 'Est_4', 'Est_5']

print('Calificaciones (filas=estudiantes, columnas=materias):')
print(calificaciones)

Calificaciones (filas=estudiantes, columnas=materias):
[[49. 76. 55. 40.]
 [89. 99. 68. 65.]
 [69. 88. 69. 89.]
 [98. 48. 49. 40.]
 [82. 80. 94. 76.]]


a) Calcula el promedio general (de todos los valores).  
b) Calcula el promedio de cada materia (por columna, `axis=0`).  
c) Calcula el promedio de cada estudiante (por fila, `axis=1`).  
d) Encuentra la nota máxima y mínima de toda la tabla.  
e) Calcula la desviación estándar por materia (`axis=0`).  
f) ¿Cuál es la mediana de la columna de Programación (columna índice 2)?

In [117]:
# --- Ejercicio 7: escribe tu código aquí ---
# a)
print(f'promedio general: {np.mean(calificaciones)}')

# b)
print(f'promedio por materia: {np.mean(calificaciones, axis=0)}')

# c)
print(f'promedio por estudiante: {np.mean(calificaciones, axis=1)}')

# d)
print(f'nota mínima: {np.min(calificaciones)}')
print(f'nota máxima: {np.max(calificaciones)}')

# e)
print(f'desviación estándar por materia: {np.std(calificaciones, axis=0).round(2)}')

# f)
print(f'mediana de la columna de Programación: {np.median(calificaciones[:,2])}')

promedio general: 71.15
promedio por materia: [77.4 78.2 67.  62. ]
promedio por estudiante: [55.   80.25 78.75 58.75 83.  ]
nota mínima: 40.0
nota máxima: 99.0
desviación estándar por materia: [17.07 17.02 15.5  19.5 ]
mediana de la columna de Programación: 68.0


---
## Parte 5 — Manejo de datos faltantes (NaN)

En datos reales es común tener valores que faltan. NumPy los representa con `np.nan`. El problema es que las funciones normales devuelven `nan` si hay aunque sea un valor faltante, por eso existen las funciones `nan*`.

### Ejercicio 8 — Trabajando con NaN (2 pts)

Vamos a simular que algunos estudiantes no rindieron ciertas materias. Metemos NaN en algunas posiciones de la matriz de calificaciones:

In [118]:
# No modifiques esta celda
calif_con_nan = calificaciones.copy()  # copia para no dañar la original
calif_con_nan[0, 2] = np.nan   # Est_1 no rindió Programación
calif_con_nan[2, 0] = np.nan   # Est_3 no rindió Matemáticas
calif_con_nan[4, 3] = np.nan   # Est_5 no rindió Estadística

print('Calificaciones con datos faltantes:')
print(calif_con_nan)

Calificaciones con datos faltantes:
[[49. 76. nan 40.]
 [89. 99. 68. 65.]
 [nan 88. 69. 89.]
 [98. 48. 49. 40.]
 [82. 80. 94. nan]]


a) Usa `np.isnan` para encontrar dónde están los valores faltantes. ¿Cuántos hay en total? (usa `np.sum` sobre el resultado de `isnan`).  
b) Intenta calcular `np.mean(calif_con_nan)`. ¿Qué resultado da? ¿Por qué?  
c) Ahora calcula la media correcta usando `np.nanmean`.  
d) Calcula `nanmin`, `nanmax` y `nanstd` de la matriz.  
e) Calcula el promedio por estudiante (por fila) ignorando los NaN.

In [136]:
# --- Ejercicio 8: escribe tu código aquí ---
# a)
print(f'valores faltantes: {np.isnan(calif_con_nan).sum()}')

# b)
print(f'np.mean(calif_con_nan) da como resultado ´nan´ porque hay valores faltantes, solo hace falta uno en una cantidad N\n'
'de datos para que no calcule correctamente, para hacerlo bien se debe usar nanmean')

# c)
print(f'media correcta (np.nanmean): {np.nanmean(calif_con_nan).round(2)}')

# d)
print(f'minimo: {np.nanmin(calif_con_nan)}')
print(f'máximo: {np.nanmax(calif_con_nan)}')
print(f'desviación: {np.nanstd(calif_con_nan).round(2)}')

# e)
print(f'promedio por estudiante: {np.nanmean(calif_con_nan, axis=1).round(2)}')

valores faltantes: 3
np.mean(calif_con_nan) da como resultado ´nan´ porque hay valores faltantes, solo hace falta uno en una cantidad N
de datos para que no calcule correctamente, para hacerlo bien se debe usar nanmean
media correcta (np.nanmean): 71.94
minimo: 40.0
máximo: 99.0
desviación: 19.79
promedio por estudiante: [55.   80.25 82.   58.75 85.33]


### Ejercicio 9 — Concatenación 2D y np.any / np.all (1.5 pts)

a) Crea dos matrices de 2×3 (puedes usar `np.random.randint`) y concaténalas verticalmente (`axis=0`). Imprime la forma resultante.  
b) Con las mismas matrices, concaténalas horizontalmente (`axis=1`). Imprime la forma resultante.  
c) Para la matriz del literal a): usa `np.any` para verificar si hay algún elemento mayor a 8. Luego usa `np.all` para verificar si todos los elementos son mayores a 0.

In [150]:
# --- Ejercicio 9: escribe tu código aquí ---
# a)
np.random.seed(5)
M1 = np.random.randint(1, 11, [2, 3])
M2 = np.random.randint(1, 11, [2, 3])

vert = np.concatenate([M1, M2], axis=0)
hor = np.concatenate([M1, M2], axis=1)

print(f'conctenadas axis=0:\n{vert}')
print(f'conctenadas axis=1:\n{hor}')

print(f'hay algún elemento mayor a 8 en vert? {np.any(vert > 8)}')
print(f'todos los elementos son mayores a 0? {np.all(vert > 0)}')

# b)

# c)

conctenadas axis=0:
[[ 4  7  7]
 [ 1 10  9]
 [ 5  8  1]
 [ 1  8  2]]
conctenadas axis=1:
[[ 4  7  7  5  8  1]
 [ 1 10  9  1  8  2]]
hay algún elemento mayor a 8 en vert? True
todos los elementos son mayores a 0? True


---
## Parte 7 — Producto matricial vs elemento a elemento

Es muy importante entender la diferencia entre `np.dot` (o `@`) y `np.multiply` (o `*`). Son operaciones completamente distintas aunque suenen parecido.

### Ejercicio 10 — np.dot vs np.multiply (2 pts)

a) Crea dos matrices aleatorias de 4×4 (valores enteros entre 1 y 10). Llámalas `A` y `B`.  
b) Calcula el producto matricial `C = np.dot(A, B)` y muéstralo.  
c) Calcula el producto elemento a elemento `D = np.multiply(A, B)` y muéstralo.  
d) Verifica que `np.dot(A, B)` da lo mismo que `A @ B` usando `np.allclose`.  
e) Verifica que `np.multiply(A, B)` da lo mismo que `A * B` usando `np.allclose`.  
f) Imprime la suma total de `C` y la suma total de `D`. ¿Son iguales? ¿Por qué?

In [ ]:
# --- Ejercicio 10: escribe tu código aquí ---

# a)

# b)

# c)

# d)

# e)

# f)

---
## Parte 8 — Copias vs vistas

Esto es un tema que da muchos dolores de cabeza si no se entiende bien: cuando haces slicing sobre un array, NO se crea un array nuevo, se crea una **vista** que comparte la misma memoria. Si modificas la vista, modificas el original.

### Ejercicio 11 — Vista vs copia (1 pt)

a) Crea un array `original = np.array([10, 20, 30, 40, 50, 60])`.  
b) Crea una vista del array: `vista = original[1:4]`. Modifica `vista[0] = 999`. Imprime `original`. ¿Cambió?  
c) Ahora crea el array de nuevo (para reiniciarlo). Crea una copia: `copia = original[1:4].copy()`. Modifica `copia[0] = 999`. Imprime `original`. ¿Cambió esta vez?

In [ ]:
# --- Ejercicio 11: escribe tu código aquí ---

# a) y b)

# c)

**Responde aquí:** ¿Cuál es la diferencia práctica entre usar slicing directo y usar `.copy()`? ¿Cuándo conviene cada uno?

*Tu respuesta:*

---
## Parte 9 — Matrices estructuradas con slicing

Aquí vamos a construir matrices con patrones específicos. La idea es usar slicing para asignar valores a bordes o regiones de la matriz.

### Ejercicio 12 — Construir matrices con patrón (2 pts)

a) Crea una matriz de 8×8 de ceros. Luego, usando slicing, llena los bordes con el valor 5 (el interior queda en 0). Imprímela.

Debería verse algo así:
```
5 5 5 5 5 5 5 5
5 0 0 0 0 0 0 5
5 0 0 0 0 0 0 5
...
5 5 5 5 5 5 5 5
```

b) Crea una matriz de 8×8 de unos. Ahora llena su diagonal con valores aleatorios entre 10 y 50. Los bordes deben quedarse en 1. Imprímela.

c) Verifica las propiedades de ambas matrices: `shape`, `dtype`, `sum` total.

In [ ]:
# --- Ejercicio 12: escribe tu código aquí ---

# a)

# b)

# c)

---
## Parte 10 — Medición de tiempos y exportación

Parte importante del análisis de datos es saber cuánto demora cada operación. Vamos a medir tiempos con `time.time()` y guardar resultados en archivos.

### Ejercicio 13 — Medir y comparar tiempos (2 pts)

a) Genera dos matrices aleatorias de 300×300 (usa `np.random.rand`).  
b) Mide el tiempo que tarda `np.dot` en multiplicarlas. Imprime el tiempo en milisegundos.  
c) Mide el tiempo que tarda `np.multiply` en multiplicarlas. Imprime el tiempo en milisegundos.  
d) ¿Cuál fue más rápida? ¿Tiene sentido considerando la complejidad de cada operación?

Recuerda el patrón:
```python
inicio = time.time()
# operacion
fin = time.time()
tiempo_ms = round((fin - inicio) * 1000, 4)
```

In [ ]:
# --- Ejercicio 13: escribe tu código aquí ---

# a)

# b)

# c)

**Responde aquí:** ¿Cuál operación fue más rápida? ¿Por qué tiene sentido ese resultado? (piensa en la complejidad O(n³) de dot vs O(n²) de multiply)

*Tu respuesta:*

### Ejercicio 14 — Guardar resultados en archivo (1.5 pts)

a) Guarda en un archivo llamado `resumen_deber.txt` lo siguiente:  
- Tiempo de `np.dot` del ejercicio anterior  
- Tiempo de `np.multiply`  
- La esquina superior izquierda (3×3) del resultado del producto matricial  

Usa el context manager `with open(...) as f:` para escribir el archivo.

b) Luego lee el archivo que acabas de crear e imprime su contenido para verificar que se guardó bien.

c) Guarda una de las matrices del ejercicio anterior en formato `.npy` con `np.save`. Luego cárgala con `np.load` y verifica que el contenido es el mismo.

In [ ]:
# --- Ejercicio 14: escribe tu código aquí ---

# a)

# b)

# c)

---
## Parte 11
## Ejercicio 15 integrador(2 puntos)

Este ejercicio junta varios conceptos.

**Contexto:** Tienes datos de sensores de temperatura de 3 estaciones meteorológicas, medidos durante 7 días. Algunos sensores fallaron y no registraron datos (NaN).

In [ ]:
# No modifiques esta celda
np.random.seed(55)
sensores = np.random.uniform(15, 35, size=(3, 7)).round(1)
# Simulamos fallos del sensor
sensores[0, 3] = np.nan
sensores[1, 5] = np.nan
sensores[2, 1] = np.nan
sensores[2, 6] = np.nan

print('Datos de sensores (3 estaciones x 7 días):')
print(sensores)

Resuelve todo en la celda de abajo:

1. ¿Cuántos datos faltantes hay en total?
2. Calcula la temperatura promedio de cada estación ignorando los NaN.
3. Calcula la temperatura máxima y mínima registrada en toda la tabla (ignorando NaN).
4. Crea un nuevo array donde los NaN se reemplacen por la media general (pista: combina `np.where` con `np.isnan`).
5. Con el array ya sin NaN, concatena una nueva fila al final que sea el promedio por día (`axis=0`), usando `np.concatenate`.
6. Guarda el array final en un archivo `sensores_completos.npy` y demuestra que se creo con el contenido.

In [ ]:
# --- Ejercicio 15 integrador: escribe tu código aquí ---

# 1)

# 2)

# 3)

# 4)

# 5)

# 6)

---
## Entrega

Antes de enviar, revisa lo siguiente:

- [ ] Escribiste tu nombre y fecha en el encabezado
- [ ] Todas las celdas de código se ejecutan sin error
- [ ] Contestaste las preguntas de texto donde se pedía
- [ ] Se generan los archivos adicionales solicitados
**Entregable:** este archivo `.ipynb` con todas las celdas ejecutadas + los archivos generados.