# 🔬 Taller Práctico — Semana 2

## NumPy: Matrices Estructuradas, np.dot vs np.multiply y Medición de Tiempos

---

| Campo          | Detalle                     |
| -------------- | --------------------------- |
| **Asignatura** | Análisis de Datos — TDSD353 |
| **Semana**     | 2 — Período 2026-A          |
| **Paralelo**   | GR2 — Martes 10:00–13:00    |
| **Docente**    | Juan Carlos Gonzalez Ortiz  |
| **Estudiante** | Alan Javier Reyes Casierra  |
| **Fecha**      | 16.04.2026                  |

---

## Objetivos

Al finalizar este taller serás capaz de:

1. Construir matrices NumPy con **bordes y patrones estructurados** usando slicing.
2. Aplicar y distinguir **`np.dot`** (multiplicación matricial) vs **`np.multiply`** (Hadamard).
3. **Medir tiempos de ejecución** con `time.time()` y guardar resultados en archivos `.txt`.

---


---

## Configuración inicial

Ejecuta esta celda primero. Importa las librerías necesarias para todo el taller.


In [1]:
import numpy as np
import time

print(" Librerías importadas correctamente")

 Librerías importadas correctamente


---

## PARTE 1 — Construcción de Matrices Estructuradas

Construir matrices con **bordes y patrones específicos** usando slicing de NumPy.  
El patrón es siempre el mismo:

1. Crear la **base** (zeros u ones)
2. Sobreescribir los **bordes** con slicing


### Actividad 1 — Matriz M1: Bordes Aleatorios, Interior = 0(1 pt)

**Objetivo:** Crear una matriz 10×10 donde los **cuatro bordes tienen valores aleatorios** (1–10) y el **interior es cero**.

![Imagen referencial](https://i.imgur.com/trLQFG2.png)





In [2]:
dim = (10, 10)

# PASO 1: Crear base de ceros
M1 = np.zeros(dim, dtype=int)

# PASO 2: Generar valores aleatorios para los bordes
aleatorios = np.random.randint(1, 11, 10)

# PASO 3: Asignar los cuatro bordes con slicing
M1[0,:] = aleatorios
M1[-1,:] = aleatorios
M1[:,0] = aleatorios
M1[:,-1] = aleatorios

print(M1)

[[8 1 3 8 7 6 6 5 1 8]
 [1 0 0 0 0 0 0 0 0 1]
 [3 0 0 0 0 0 0 0 0 3]
 [8 0 0 0 0 0 0 0 0 8]
 [7 0 0 0 0 0 0 0 0 7]
 [6 0 0 0 0 0 0 0 0 6]
 [6 0 0 0 0 0 0 0 0 6]
 [5 0 0 0 0 0 0 0 0 5]
 [1 0 0 0 0 0 0 0 0 1]
 [6 1 3 8 7 6 6 5 1 6]]


**Reflexión A1:** ¿Qué pasa si usas `M1[1:-1, 1:-1]`? ¿Qué parte de la matriz accede?


In [3]:
print('Accede a la parte central, a los zeros')

Accede a la parte central, a los zeros


---

### Actividad 2 — Matriz M2: Bordes = 0, Interior Aleatorio(1 pt)

**Objetivo:** Crear la matriz **inversa a M1**: ahora el interior tiene valores aleatorios y los bordes son cero.  
![Imagen referencial](https://i.imgur.com/RiwlS39.png[/img])


In [4]:
# PASO 1: Crear base con valores aleatorios en toda la matriz
M2_a = np.random.randint(1, 11, dim)

# PASO 2: Sobreescribir los cuatro bordes con cero
zeros_a = np.zeros(10, dtype=int)
M2_a[0,:] = zeros_a
M2_a[-1,:] = zeros_a
M2_a[:,0] = zeros_a
M2_a[:,-1] = zeros_a
print(f"FORMA A:\n{M2_a}\n")

'''
otra forma de hacerlo
paso 1: usar una matriz 10x10 de ceros
paso 2: crear una matriz 8x8 de aleatorios
paso 3: reemplazar con slicing la matriz de aleatorios en la matriz de ceros
'''

M2_b = np.zeros(dim, dtype=int)
aleatorios_b = np.random.randint(1, 11, [8, 8])
M2_b[1:-1, 1:-1] = aleatorios_b
print(f"FORMA B:\n{M2_b}")

FORMA A:
[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  9  6  4 10 10  8  1  1  0]
 [ 0  5  2  8  6 10  1  9  3  0]
 [ 0  3  5  2  8  8  3  4 10  0]
 [ 0  8  3  8  5  4  9  7 10  0]
 [ 0  5  5  6  9  6  3 10  1  0]
 [ 0  1  3  7  2  1  6  8  2  0]
 [ 0  6  5  3  8  5  2  1  2  0]
 [ 0 10 10  9  7  9  6  8  2  0]
 [ 0  0  0  0  0  0  0  0  0  0]]

FORMA B:
[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  1  1  9  1  1  5  3 10  0]
 [ 0  4  8  5  2  8  6  3  9  0]
 [ 0  6 10  6 10  4  8  2  6  0]
 [ 0  1  2 10  7  7  1  6  9  0]
 [ 0  3  1  1  5 10  6  3  2  0]
 [ 0  7  9  4  6  4 10  9  3  0]
 [ 0  4  8  8 10  4  6  5  8  0]
 [ 0 10  3  7  5  1  4  1  9  0]
 [ 0  0  0  0  0  0  0  0  0  0]]


Reto: No puntua, pero, como harias para hacer una matriz de ceros de (10x10) en donde solo en la diagonal van a ir numeros aleatorios?

In [5]:
# con matriz identidad y multiplicar por los aleatorios
aleatorios_identidad = np.random.randint(1, 11, 10)

identidad = np.eye(10, dtype=int) * aleatorios_identidad
print(identidad)

[[1 0 0 0 0 0 0 0 0 0]
 [0 7 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 5 0 0 0 0 0 0]
 [0 0 0 0 8 0 0 0 0 0]
 [0 0 0 0 0 6 0 0 0 0]
 [0 0 0 0 0 0 7 0 0 0]
 [0 0 0 0 0 0 0 3 0 0]
 [0 0 0 0 0 0 0 0 6 0]
 [0 0 0 0 0 0 0 0 0 5]]


---

### ✏️ Actividad 3 — Inspección de Matrices(1 pt)

Antes de operar, siempre debemos **verificar las propiedades** de nuestros arrays. Para M1 y M2, obten el shape, dtype, el size, valor minimo, valor maximo, y la sumatoria total


In [6]:
'''
todos los resultados se mantienen porque siguen la misma regla: matriz de 10x10
cambiarían los máximos y mínimos si los números aleatorios tuvieran rangos distintos, la sumatoria total siempre varía
porque los valores son diferentes en M1, M2_a y M2_b
'''

print('Para M1:')
print(f'  shape: {M1.shape}')
print(f'  dtype: {M1.dtype}')
print(f'  size: {M1.size}')
print(f'  valor mínimo: {M1.min()}')
print(f'  valor máximo: {M1.max()}')
print(f'  sumatoria total: {M1.sum()}')

print('Para M2_a:')
print(f'  shape: {M2_a.shape}')
print(f'  dtype: {M2_a.dtype}')
print(f'  size: {M2_a.size}')
print(f'  valor mínimo: {M2_a.min()}')
print(f'  valor máximo: {M2_a.max()}')
print(f'  sumatoria total: {M2_a.sum()}')

print('Para M2_b:')
print(f'  shape: {M2_b.shape}')
print(f'  dtype: {M2_b.dtype}')
print(f'  size: {M2_b.size}')
print(f'  valor mínimo: {M2_b.min()}')
print(f'  valor máximo: {M2_b.max()}')
print(f'  sumatoria total: {M2_b.sum()}')

Para M1:
  shape: (10, 10)
  dtype: int64
  size: 100
  valor mínimo: 0
  valor máximo: 8
  sumatoria total: 176
Para M2_a:
  shape: (10, 10)
  dtype: int32
  size: 100
  valor mínimo: 0
  valor máximo: 10
  sumatoria total: 358
Para M2_b:
  shape: (10, 10)
  dtype: int64
  size: 100
  valor mínimo: 0
  valor máximo: 10
  sumatoria total: 347


---

## PARTE 2 — np.dot vs np.multiply




### ✏️ Actividad 4 — Calcular M3 = np.dot(M1, M2) y obten el maximo y minimo valor de la matriz M3(1 pt)


In [7]:
# solo se usará M2_a
# uso de time.time() para el resultado de la actividad 6
inicio = time.time()
M3 = np.dot(M1, M2_a)
print('PARA M3:')
print(M3)
print(f'  valor mínimo: {M3.min()}')
print(f'  valor máximo: {M3.max()}')
fin = time.time()
duracion_dot = round((fin - inicio) * 1000, 5)

PARA M3:
[[  0 180 156 202 240 208 168 230 190   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0 180 156 202 240 208 168 230 190   0]]
  valor mínimo: 0
  valor máximo: 240


### ✏️ Actividad 5 — Calcular M4 = np.multiply(M1, M2) y obten el maximo y minimo valor de la matriz M3(1 pt)


In [8]:
inicio = time.time()
M4 = np.multiply(M1, M2_a)
print('PARA M4:')
print(M4)
print(f'  valor mínimo: {M4.min()}')
print(f'  valor máximo: {M4.max()}')
fin = time.time()
duracion_mult = round((fin - inicio) * 1000, 5)

PARA M4:
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
  valor mínimo: 0
  valor máximo: 0


---

## PARTE 3 — Medición de Tiempos y Archivos .txt

Usa `time.time()` para medir el costo computacional de cada operación y guardaremos los resultados en archivos de texto.

**Patrón de medición:**

```python
inicio = time.time()
# ← operación a medir →
fin = time.time()
duracion = round((fin - inicio) * 1000, 5)  # en milisegundos
```


### ✏️ Actividad 6 — Medir Tiempos de np.dot y np.multiply usando M1 y M2 e indicar cual fue más rapido(1 pt)


In [9]:
print(f'Duración en milisegundos de dot: {duracion_dot}')
print(f'Duración en milisegundos de multiply: {duracion_mult}')

if duracion_dot > duracion_mult:
    print('> Duracion_multiply fue más rápido')
else:
    print('> Duracion_dot fue más rápido')

Duración en milisegundos de dot: 2.51913
Duración en milisegundos de multiply: 2.35748
> Duracion_multiply fue más rápido


Con matrices 10×10 los tiempos son muy pequeños (microsegundos). Para ver diferencias más claras, ejecutemos con matrices más grandes. Crea una Matriz de datos aleatorios de 1000 x 1000 (un millón de elementos)(no uses semilla) y vuelve a calcular el tiempo y realizar el dot y multiply y compara tiempos


In [10]:
M_grande = np.random.randint(1, 500, [1000, 1000])

inicio_dot = time.time()
M_grande_dot = np.dot(M_grande, M_grande)
fin_dot = time.time()
duracion_dot_g = round(fin_dot - inicio_dot, 5)

inicio_mult = time.time()
M_grande_mult = np.multiply(M_grande, M_grande)
fin_mult = time.time()
duracion_mult_g = round(fin_mult - inicio_mult, 5)

print(f'Duración en segundos de dot: {duracion_dot_g}')
print(f'Duración en segundos de multiply: {duracion_mult_g}')

if duracion_dot_g > duracion_mult_g:
    print('> duracion_mult_g fue más rápido')
else:
    print('> duracion_dot_g fue más rápido')

Duración en segundos de dot: 0.93541
Duración en segundos de multiply: 0.00159
> duracion_mult_g fue más rápido


---

### ✏️ Actividad 7 — Guardar el resultado de la actividad 6 en un archivo txt llamado resultado1.txt. En este archivo solo debe imprimirse en texto el tiempo que demoro la operacion multiply, el tiempo que demoro dot y la diferencia de tiempo que hubo entre estas dos operaciones.(1 pt)




In [11]:
diferencia = duracion_dot_g - duracion_mult_g

with open('resultado1.txt', 'w') as f:
    f.write(f'DURACION\ndot: {duracion_dot_g} | multiply: {duracion_mult_g} | diferencia: {diferencia}')

 ### ✏️ Actividad 8-Guarda la matriz de un millon de datos en el formato .npy llamado resultado2.npy ya que es más rápido y ocupa menos espacio comparado con un txt.(1 pt)

In [12]:
np.save('resultado2.npy', M_grande)

## Actividad 9. Historia de la UEFA Champions League

Trabajarás con el **histórico completo de finales de la UEFA Champions League** desde su primera edición en 1956 hasta 2025. El archivo `champions_league.csv` contiene las siguientes columnas:

| Columna | Tipo | Descripción |
|---|---|---|
| `Anio` | numérico | Año de la final |
| `Campeon` | texto | Club campeón |
| `Finalista` | texto | Club subcampeón |
| `Goles_campeon` | numérico | Goles del campeón en la final |
| `Goles_finalista` | numérico | Goles del finalista en la final |
| `Asistencia` | numérico | Espectadores en el estadio |
| `Pais_campeon` | texto | País del club campeón |

> ⚠️ El dataset contiene **datos faltantes** en algunas columnas numéricas. Parte de los ejercicios consiste en identificarlos y manejarlos correctamente.

---

**Instrucciones generales:**
- Completa cada celda donde aparezca `# TU CÓDIGO AQUÍ` y donde veas ... (3 puntos seguidos)
- Trabaja en orden: cada parte puede depender de las anteriores.
- Coloca `champions_league.csv` en la misma carpeta que este cuaderno.

---
## PARTE 4 — Importación de Datos

### Ejercicio 9.1 — Cargar el dataset numérico(1 pt)

Usa `np.genfromtxt()` para leer el archivo `champions_league.csv` y cargar **únicamente las columnas numéricas** en un array llamado `datos`.

Las columnas numéricas y sus índices en el CSV son:

| Índice CSV | Columna |
|:---:|---|
| 0 | `Anio` |
| 3 | `Goles_campeon` |
| 4 | `Goles_finalista` |
| 5 | `Asistencia` |

Usa `dtype=float` para que las celdas vacías queden como `np.nan`.

In [13]:
datos = np.genfromtxt('champions_league.csv',
                      delimiter=',',
                      usecols=(0, 3, 4, 5),
                      skip_header=1,
                      dtype=float
                      )

### Ejercicio 1.2 — Cargar los nombres de los campeones(1 pt)

Crea un array separado llamado `campeones` que contenga **solo la columna de texto `Campeon`** (columna índice 1 del CSV), cargada como tipo `str`.

> 💡 Usa `dtype=str` y `usecols=(1,)` en `genfromtxt()`.

In [14]:
#Aquí debes leer solo la columna de texto Campeon del CSV.
campeones = np.genfromtxt('champions_league.csv',
                          delimiter=',',
                          usecols=1,
                          dtype=str
                          )

---
## PARTE 5 — Tratamiento de Datos Faltantes

### Ejercicio 2.1 — Diagnóstico de NaN(1 pt)

Determina:

a) ¿Cuántos valores `NaN` hay en total en el array `datos`?  
b) ¿Cuántos `NaN` hay en cada columna?  
c) ¿En qué años hay datos faltantes? Filtra las filas con NaN y muestra sus años.

In [15]:
print(f'a) {np.isnan(datos).sum()}')
print(f'b) {np.isnan(datos).sum(axis=0)}')
filas_con_nan = datos[np.isnan(datos).any(axis=1)]
print(f'c) {filas_con_nan[:,0]}')

a) 14
b) [0 2 6 6]
c) [2017. 2009. 2004. 2002. 1993. 1987. 1985. 1983. 1977. 1975. 1970. 1966.
 1962. 1957.]


### Ejercicio 9.2 — Imputar datos faltantes(1 pt)

9.2.1 .Crea una copia del array llamada `datos_limpios` donde:
- Los `NaN` en `Goles_campeon` (col 1) se reemplacen por la **mediana** de esa columna.
- Los `NaN` en `Goles_finalista` (col 2) se reemplacen por la **mediana** de esa columna.
- Los `NaN` en `Asistencia` (col 3) se reemplacen por el **promedio** de esa columna.

> 💡 Usa `np.nanmedian()`, `np.nanmean()` y `np.where()`.

In [16]:
datos_limpios = np.copy(datos)
mediana_campeon = np.nanmedian(datos_limpios[:,1])
mediana_finalista = np.nanmedian(datos_limpios[:,2])
promedio_asistencia = np.nanmean(datos_limpios[:,3])

datos_limpios[:,1] = np.where(
    np.isnan(datos_limpios[:,1]),
    mediana_campeon,
    datos_limpios[:,1]
)

datos_limpios[:,2] = np.where(
    np.isnan(datos_limpios[:,2]),
    mediana_finalista,
    datos_limpios[:,2]
)

datos_limpios[:,3] = np.where(
    np.isnan(datos_limpios[:,3]),
    promedio_asistencia,
    datos_limpios[:,3]
)

9.2.2 Ejercicio  ( 1 pt)
Consulta sobre .npz en numpy y mandar a guardar datos_limpios en formato .csv incluyendo las cabeceras de cada columna y los datos

In [17]:
'''
.npz es un archivo comprimido (como en zip de numpy) que guarda uno o varios arrays
puede usar np.savez() o np.savez_compressed()
'''

np.savez('datosfin.npz', datos=datos_limpios)

np.savetxt('datosfin.csv',
           datos_limpios,
           delimiter=',',
           header='Anio,Goles_campeon,Goles_finalista,Asistencia',
           fmt='%d'
           )

---
## ✅ Checklist de Entrega

Antes de enviar tu notebook, verifica que:

- [ ] El encabezado tiene tu nombre y fecha
- [ ] Todas las celdas de código se ejecutaron sin error (`Kernel > Restart & Run All`)


---

**Entregable:** Este archivo `.ipynb` con todas las celdas ejecutadas + los archivos que se deben generar 

> _Docente: Juan Carlos Gonzalez Ortiz — TDSD353 Análisis de Datos — ESFOT-EPN 2026-A
